import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AbacusIcon ("abacus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AbacusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="3.5" width="18" height="17" rx="1.5" />
      <line x1="6.5" y1="3.5" x2="6.5" y2="20.5" />
      <line x1="6.5" y1="8" x2="10.5" y2="8" />
      <line x1="6.5" y1="12" x2="9" y2="12" />
      <line x1="6.5" y1="16" x2="11" y2="16" />
      <circle cx="9" cy="8" r="1" fill="currentColor" stroke="none" />
      <circle cx="8" cy="12" r="1" fill="currentColor" stroke="none" />
      <circle cx="10" cy="16" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

AbacusIcon.displayName = "AbacusIcon";

export default AbacusIcon;
