import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AccessibilityIcon ("accessibility")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AccessibilityIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="4.5" r="1.8" />
      <path d="M4 8.5 12 10l8-1.5" />
      <line x1="12" y1="10" x2="12" y2="14" />
      <path d="M8 21l3-6.5" />
      <path d="M16 21l-3-6.5" />
      <path d="M9 13h6" />
    </IconBase>
  )
);

AccessibilityIcon.displayName = "AccessibilityIcon";

export default AccessibilityIcon;
