import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ActivityIcon ("activity")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ActivityIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="3 12 8 12 10 6 14 18 16 12 21 12" />
    </IconBase>
  )
);

ActivityIcon.displayName = "ActivityIcon";

export default ActivityIcon;
