import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AlarmClockIcon ("alarm-clock")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AlarmClockIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="13.5" r="8" />
      <line x1="12" y1="13.5" x2="12" y2="9.5" />
      <line x1="12" y1="13.5" x2="15" y2="15" />
      <line x1="4" y1="4" x2="6.5" y2="6.5" />
      <line x1="20" y1="4" x2="17.5" y2="6.5" />
      <line x1="9" y1="2" x2="15" y2="2" />
    </IconBase>
  )
);

AlarmClockIcon.displayName = "AlarmClockIcon";

export default AlarmClockIcon;
