import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AlignVerticalIcon ("align-vertical")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AlignVerticalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="12" x2="20" y2="12" />
      <rect x="9" y="4" width="6" height="5" rx="1" />
      <rect x="9" y="15" width="6" height="5" rx="1" />
    </IconBase>
  )
);

AlignVerticalIcon.displayName = "AlignVerticalIcon";

export default AlignVerticalIcon;
