import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AmpersandIcon ("ampersand")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AmpersandIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M18 20 8 8a3 3 0 1 1 5-3c0 2-1 3-3 4-3 1.5-4 3-4 5a4 4 0 0 0 7 2.5l2-2.5" />
      <line x1="15" y1="14" x2="18" y2="17" />
    </IconBase>
  )
);

AmpersandIcon.displayName = "AmpersandIcon";

export default AmpersandIcon;
