import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AnchorIcon ("anchor")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AnchorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="5.5" r="2" />
      <line x1="12" y1="7.5" x2="12" y2="20.5" />
      <path d="M5.5 14a6.5 6.5 0 0 0 13 0" />
      <line x1="4" y1="14" x2="7" y2="14" />
      <line x1="17" y1="14" x2="20" y2="14" />
    </IconBase>
  )
);

AnchorIcon.displayName = "AnchorIcon";

export default AnchorIcon;
