import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AngryIcon ("angry")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AngryIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <line x1="8" y1="9" x2="10.5" y2="10.5" />
      <line x1="16" y1="9" x2="13.5" y2="10.5" />
      <path d="M8 16.5a4.5 4 0 0 1 8 0" />
    </IconBase>
  )
);

AngryIcon.displayName = "AngryIcon";

export default AngryIcon;
