import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AntennaIcon ("antenna")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AntennaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="2.5" x2="12" y2="21.5" />
      <path d="M6 8a8.5 8.5 0 0 1 12 0" />
      <path d="M3.5 5a12 12 0 0 1 17 0" />
      <circle cx="12" cy="2.5" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

AntennaIcon.displayName = "AntennaIcon";

export default AntennaIcon;
