import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AppleFruitIcon ("apple-fruit")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AppleFruitIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 8.5c-3-3-8-1.5-8 4a8 8 0 0 0 8 8 8 8 0 0 0 8-8c0-5.5-5-5.5-8-4Z" />
      <path d="M12 8.5V5.5" />
      <path d="M12 5.5c0-1.5 1-2 2.5-2" />
    </IconBase>
  )
);

AppleFruitIcon.displayName = "AppleFruitIcon";

export default AppleFruitIcon;
