import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowShapeIcon ("arrow-shape")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowShapeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2 12 12 4v5h10v6H12v5Z" />
    </IconBase>
  )
);

ArrowShapeIcon.displayName = "ArrowShapeIcon";

export default ArrowShapeIcon;
