import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowUpLeftIcon ("arrow-up-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowUpLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="18" y1="18" x2="6" y2="6" />
      <polyline points="15 6 6 6 6 15" />
    </IconBase>
  )
);

ArrowUpLeftIcon.displayName = "ArrowUpLeftIcon";

export default ArrowUpLeftIcon;
