import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowRightIcon ("arrow-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="12" x2="19" y2="12" />
      <polyline points="14 6 20 12 14 18" />
    </IconBase>
  )
);

ArrowRightIcon.displayName = "ArrowRightIcon";

export default ArrowRightIcon;
