import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowUpIcon ("arrow-up")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowUpIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="20" x2="12" y2="5" />
      <polyline points="6 10 12 4 18 10" />
    </IconBase>
  )
);

ArrowUpIcon.displayName = "ArrowUpIcon";

export default ArrowUpIcon;
