import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowLeftIcon ("arrow-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="20" y1="12" x2="5" y2="12" />
      <polyline points="10 6 4 12 10 18" />
    </IconBase>
  )
);

ArrowLeftIcon.displayName = "ArrowLeftIcon";

export default ArrowLeftIcon;
