import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowDownRightIcon ("arrow-down-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowDownRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="6" y1="6" x2="18" y2="18" />
      <polyline points="18 9 18 18 9 18" />
    </IconBase>
  )
);

ArrowDownRightIcon.displayName = "ArrowDownRightIcon";

export default ArrowDownRightIcon;
