import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowDownLeftIcon ("arrow-down-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowDownLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="18" y1="6" x2="6" y2="18" />
      <polyline points="6 9 6 18 15 18" />
    </IconBase>
  )
);

ArrowDownLeftIcon.displayName = "ArrowDownLeftIcon";

export default ArrowDownLeftIcon;
