import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ArrowDownIcon ("arrow-down")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ArrowDownIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="4" x2="12" y2="19" />
      <polyline points="6 14 12 20 18 14" />
    </IconBase>
  )
);

ArrowDownIcon.displayName = "ArrowDownIcon";

export default ArrowDownIcon;
