import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AsteriskIcon ("asterisk")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AsteriskIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="4" x2="12" y2="20" />
      <line x1="5" y1="7.5" x2="19" y2="16.5" />
      <line x1="19" y1="7.5" x2="5" y2="16.5" />
    </IconBase>
  )
);

AsteriskIcon.displayName = "AsteriskIcon";

export default AsteriskIcon;
