import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * AtomIcon ("atom")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const AtomIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="1.4" fill="currentColor" stroke="none" />
      <path d="M3 12a9 3.5 0 1 0 18 0 9 3.5 0 1 0 -18 0" />
      <path d="M3 12a9 3.5 60 1 0 18 0 9 3.5 60 1 0 -18 0" />
      <path d="M3 12a9 3.5 120 1 0 18 0 9 3.5 120 1 0 -18 0" />
    </IconBase>
  )
);

AtomIcon.displayName = "AtomIcon";

export default AtomIcon;
