import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BabyIcon ("baby")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BabyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="7" r="3.5" />
      <path d="M6 20a6 5 0 0 1 12 0" />
      <line x1="9" y1="6.5" x2="9" y2="7" />
      <line x1="15" y1="6.5" x2="15" y2="7" />
      <path d="M10 8.5a2 1.3 0 0 0 4 0" />
    </IconBase>
  )
);

BabyIcon.displayName = "BabyIcon";

export default BabyIcon;
