import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BackslashIcon ("backslash")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BackslashIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="6" y1="4" x2="18" y2="20" />
    </IconBase>
  )
);

BackslashIcon.displayName = "BackslashIcon";

export default BackslashIcon;
