import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BackpackIcon ("backpack")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BackpackIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 8V6a5 5 0 0 1 10 0v2" />
      <path d="M5 8h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2Z" />
      <rect x="9" y="12" width="6" height="4" rx="1" />
      <line x1="9" y1="8" x2="9" y2="10" />
      <line x1="15" y1="8" x2="15" y2="10" />
    </IconBase>
  )
);

BackpackIcon.displayName = "BackpackIcon";

export default BackpackIcon;
