import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BadgeIcon ("badge")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BadgeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5 14.5 5H18a1.5 1.5 0 0 1 1.5 1.5V10l2 2-2 2v3.5A1.5 1.5 0 0 1 18 19h-3.5L12 21.5 9.5 19H6a1.5 1.5 0 0 1-1.5-1.5V14l-2-2 2-2V5.5A1.5 1.5 0 0 1 6 4h3.5Z" />
    </IconBase>
  )
);

BadgeIcon.displayName = "BadgeIcon";

export default BadgeIcon;
