import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BadgePercentIcon ("badge-percent")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BadgePercentIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5 14.5 5H18a1.5 1.5 0 0 1 1.5 1.5V10l2 2-2 2v3.5A1.5 1.5 0 0 1 18 19h-3.5L12 21.5 9.5 19H6a1.5 1.5 0 0 1-1.5-1.5V14l-2-2 2-2V5.5A1.5 1.5 0 0 1 6 4h3.5Z" />
      <line x1="15" y1="9" x2="9" y2="15" />
      <circle cx="9.7" cy="9.7" r="1" fill="currentColor" stroke="none" />
      <circle cx="14.3" cy="14.3" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

BadgePercentIcon.displayName = "BadgePercentIcon";

export default BadgePercentIcon;
