import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BagIcon ("bag")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BagIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 8h12l1 12.5H5Z" />
      <path d="M9 8V6a3 3 0 0 1 6 0v2" />
    </IconBase>
  )
);

BagIcon.displayName = "BagIcon";

export default BagIcon;
