import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BalloonIcon ("balloon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BalloonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3a6 7 0 0 1 6 7c0 4-3 6.5-4.5 7.5L15 19h-6l1.5-1.5C9 16.5 6 14 6 10a6 7 0 0 1 6-7Z" />
      <path d="M11 19q1 1.5 0 2.5" />
    </IconBase>
  )
);

BalloonIcon.displayName = "BalloonIcon";

export default BalloonIcon;
