import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BananaIcon ("banana")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BananaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 4c-1 6 0 13 6 15.5 5 2 9-.5 10-5" />
      <path d="M19 3.5c1 1.5 1.5 3 .5 5" />
    </IconBase>
  )
);

BananaIcon.displayName = "BananaIcon";

export default BananaIcon;
