import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BandageIcon ("bandage")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BandageIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="9" width="18" height="6" rx="3" />
      <line x1="9" y1="9" x2="9" y2="15" />
      <line x1="15" y1="9" x2="15" y2="15" />
      <circle cx="6" cy="12" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="18" cy="12" r="0.6" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

BandageIcon.displayName = "BandageIcon";

export default BandageIcon;
