import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BankIcon ("bank")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BankIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polygon points="12 3 21 8.5 3 8.5" />
      <line x1="4" y1="8.5" x2="20" y2="8.5" />
      <line x1="5.5" y1="8.5" x2="5.5" y2="18" />
      <line x1="10" y1="8.5" x2="10" y2="18" />
      <line x1="14" y1="8.5" x2="14" y2="18" />
      <line x1="18.5" y1="8.5" x2="18.5" y2="18" />
      <line x1="3.5" y1="18" x2="20.5" y2="18" />
      <line x1="3" y1="21" x2="21" y2="21" />
    </IconBase>
  )
);

BankIcon.displayName = "BankIcon";

export default BankIcon;
