import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BarcodeIcon ("barcode")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BarcodeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="3.5" y1="4" x2="3.5" y2="20" />
      <line x1="6.5" y1="4" x2="6.5" y2="20" />
      <line x1="9" y1="4" x2="9" y2="20" />
      <line x1="12" y1="4" x2="12" y2="20" />
      <line x1="14.5" y1="4" x2="14.5" y2="20" />
      <line x1="17.5" y1="4" x2="17.5" y2="20" />
      <line x1="20.5" y1="4" x2="20.5" y2="20" />
    </IconBase>
  )
);

BarcodeIcon.displayName = "BarcodeIcon";

export default BarcodeIcon;
