import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BatteryLowIcon ("battery-low")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BatteryLowIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="8" width="17" height="8" rx="1.5" />
      <line x1="21.5" y1="10.5" x2="21.5" y2="13.5" />
      <rect x="5" y="10.2" width="2" height="3.6" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

BatteryLowIcon.displayName = "BatteryLowIcon";

export default BatteryLowIcon;
