import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BatteryChargingIcon ("battery-charging")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BatteryChargingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="8" width="17" height="8" rx="1.5" />
      <line x1="21.5" y1="10.5" x2="21.5" y2="13.5" />
      <polyline points="11.5 9.5 8.5 12.5 11 12.5 9.5 15" />
    </IconBase>
  )
);

BatteryChargingIcon.displayName = "BatteryChargingIcon";

export default BatteryChargingIcon;
