import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BedIcon ("bed")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BedIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 19v-8a2 2 0 0 1 2-2h15a2 2 0 0 1 2 2v8" />
      <path d="M2.5 15h19" />
      <path d="M5.5 12V9a1.5 1.5 0 0 1 1.5-1.5h3A1.5 1.5 0 0 1 11.5 9v3" />
      <line x1="2.5" y1="19" x2="2.5" y2="21" />
      <line x1="21.5" y1="19" x2="21.5" y2="21" />
    </IconBase>
  )
);

BedIcon.displayName = "BedIcon";

export default BedIcon;
