import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BellOffIcon ("bell-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BellOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9.5 5.5A6 6 0 0 1 18 11v5l1.5 3H8" />
      <path d="M6 10a6 6 0 0 0-1.5 4l-1.5 3h4" />
      <path d="M10 21a2 2 0 0 0 4 0" />
      <line x1="3" y1="3" x2="21" y2="21" />
    </IconBase>
  )
);

BellOffIcon.displayName = "BellOffIcon";

export default BellOffIcon;
