import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BellIcon ("bell")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BellIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 10a6 6 0 0 1 12 0v5l1.5 3h-15L6 15Z" />
      <path d="M10 21a2 2 0 0 0 4 0" />
    </IconBase>
  )
);

BellIcon.displayName = "BellIcon";

export default BellIcon;
