import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BikeIcon ("bike")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BikeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="17" r="3.3" />
      <circle cx="18" cy="17" r="3.3" />
      <path d="M6 17 10 9h5l3 8" />
      <path d="M10 9 12.5 13H18" />
      <line x1="10" y1="9" x2="13" y2="9" />
    </IconBase>
  )
);

BikeIcon.displayName = "BikeIcon";

export default BikeIcon;
