import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BiohazardIcon ("biohazard")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BiohazardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="1.7" />
      <circle cx="12" cy="5.5" r="2.3" />
      <circle cx="6.8" cy="15.2" r="2.3" />
      <circle cx="17.2" cy="15.2" r="2.3" />
      <path d="M12 9v3l-2.5 1.5" />
      <path d="M12 12l2.5 1.5" />
      <path d="M9.5 13.5 8 12" />
    </IconBase>
  )
);

BiohazardIcon.displayName = "BiohazardIcon";

export default BiohazardIcon;
