import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BirdIcon ("bird")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BirdIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 15c1-5 5-8 10-8 3 0 6 1.5 7 3.5-2-.5-3 0-3 1.5 0 5-5 9-11 9-2 0-3.5-.5-4.5-1.5 1.5 0 3-.5 3.5-1.5-1 0-1.7-.5-2-3Z" />
      <circle cx="16.5" cy="9" r="0.7" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

BirdIcon.displayName = "BirdIcon";

export default BirdIcon;
