import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BlenderIcon ("blender")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BlenderIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5h8l-1 8H9Z" />
      <path d="M7 11.5h10l-1 8a1.5 1.5 0 0 1-1.5 1.3h-6A1.5 1.5 0 0 1 7 19.5Z" />
      <line x1="10" y1="6" x2="14" y2="6" />
    </IconBase>
  )
);

BlenderIcon.displayName = "BlenderIcon";

export default BlenderIcon;
