import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BlobIcon ("blob")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BlobIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3c4 0 8 2 8 6.5 0 3.5-2.5 5-2.5 8-.5 3-3 4.5-6 4.5s-6-2-7-5-1-6 .5-8.5S8 3 12 3Z" />
    </IconBase>
  )
);

BlobIcon.displayName = "BlobIcon";

export default BlobIcon;
