import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BluetoothIcon ("bluetooth")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BluetoothIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 7 17 15l-5 4V5l5 4L7 17" />
    </IconBase>
  )
);

BluetoothIcon.displayName = "BluetoothIcon";

export default BluetoothIcon;
