import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BoldIcon ("bold")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BoldIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 4h6a4 3.5 0 0 1 0 7h-6Z" />
      <path d="M6.5 11h7a4 3.5 0 0 1 0 7h-7Z" />
    </IconBase>
  )
);

BoldIcon.displayName = "BoldIcon";

export default BoldIcon;
