import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BookmarkCheckIcon ("bookmark-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BookmarkCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 3.5h11a1 1 0 0 1 1 1V21l-6.5-4-6.5 4V4.5a1 1 0 0 1 1-1Z" />
      <polyline points="9 9.5 11 11.5 15 7.5" />
    </IconBase>
  )
);

BookmarkCheckIcon.displayName = "BookmarkCheckIcon";

export default BookmarkCheckIcon;
