import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BookIcon ("book")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BookIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 4.5A1.5 1.5 0 0 1 5.5 3H19v17H5.5A1.5 1.5 0 0 1 4 18.5Z" />
      <line x1="8" y1="3" x2="8" y2="20" />
    </IconBase>
  )
);

BookIcon.displayName = "BookIcon";

export default BookIcon;
