import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BottleIcon ("bottle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BottleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M10 2.5h4v3.5l1.5 2v12a1.5 1.5 0 0 1-1.5 1.5h-4A1.5 1.5 0 0 1 8.5 20V8l1.5-2Z" />
      <line x1="8.5" y1="11" x2="15.5" y2="11" />
    </IconBase>
  )
);

BottleIcon.displayName = "BottleIcon";

export default BottleIcon;
