import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BoxesIcon ("boxes")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BoxesIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5 18 6v6l-6 3.5L6 12V6Z" />
      <path d="M3 15l4-2.3 4 2.3v5l-4 2.3-4-2.3Z" />
      <path d="M13 15l4-2.3 4 2.3v5l-4 2.3-4-2.3Z" />
    </IconBase>
  )
);

BoxesIcon.displayName = "BoxesIcon";

export default BoxesIcon;
