import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BracketsIcon ("brackets")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BracketsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5H5.5v17H8" />
      <path d="M16 3.5h2.5v17H16" />
    </IconBase>
  )
);

BracketsIcon.displayName = "BracketsIcon";

export default BracketsIcon;
