import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BracesIcon ("braces")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BracesIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5a2.5 2.5 0 0 0-2.5 2.5v3a2 2 0 0 1-2 2 2 2 0 0 1 2 2v3A2.5 2.5 0 0 0 8 18.5" />
      <path d="M16 3.5a2.5 2.5 0 0 1 2.5 2.5v3a2 2 0 0 0 2 2 2 2 0 0 0-2 2v3a2.5 2.5 0 0 1-2.5 2.5" />
    </IconBase>
  )
);

BracesIcon.displayName = "BracesIcon";

export default BracesIcon;
