import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BrainIcon ("brain")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BrainIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 4.5A3.5 3.5 0 0 0 5.5 8 3 3 0 0 0 4 13a3.5 3.5 0 0 0 3 5.4A3 3 0 0 0 12 20V6a3.5 3.5 0 0 0-3-1.5Z" />
      <path d="M15 4.5A3.5 3.5 0 0 1 18.5 8 3 3 0 0 1 20 13a3.5 3.5 0 0 1-3 5.4A3 3 0 0 1 12 20V6a3.5 3.5 0 0 1 3-1.5Z" />
    </IconBase>
  )
);

BrainIcon.displayName = "BrainIcon";

export default BrainIcon;
