import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BridgeIcon ("bridge")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BridgeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2 15c2-6 6-9 10-9s8 3 10 9" />
      <line x1="4" y1="15" x2="4" y2="20" />
      <line x1="20" y1="15" x2="20" y2="20" />
      <line x1="2" y1="20" x2="22" y2="20" />
      <line x1="8" y1="10.5" x2="8" y2="20" />
      <line x1="16" y1="10.5" x2="16" y2="20" />
    </IconBase>
  )
);

BridgeIcon.displayName = "BridgeIcon";

export default BridgeIcon;
