import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BrushIcon ("brush")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BrushIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M15 4 20 9l-7.5 7.5a2.5 2.5 0 0 1-3.5 0l-1-1a2.5 2.5 0 0 1 0-3.5Z" />
      <path d="M8 15.5c-1 1-1 2.5-3.5 3.5 1-2.5.5-3.5 1.5-4.5" />
    </IconBase>
  )
);

BrushIcon.displayName = "BrushIcon";

export default BrushIcon;
