import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BugIcon ("bug")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BugIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="7" y="8.5" width="10" height="10" rx="4" />
      <line x1="12" y1="5" x2="12" y2="8.5" />
      <line x1="4.5" y1="12" x2="7" y2="12" />
      <line x1="17" y1="12" x2="19.5" y2="12" />
      <line x1="5.5" y1="8" x2="7.5" y2="9.7" />
      <line x1="18.5" y1="8" x2="16.5" y2="9.7" />
      <line x1="5.5" y1="18.5" x2="7.5" y2="16.8" />
      <line x1="18.5" y1="18.5" x2="16.5" y2="16.8" />
    </IconBase>
  )
);

BugIcon.displayName = "BugIcon";

export default BugIcon;
