import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * Building2Icon ("building-2")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const Building2Icon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="9" width="8" height="12" rx="1" />
      <rect x="12" y="3" width="9" height="18" rx="1" />
      <line x1="5.5" y1="12.5" x2="7" y2="12.5" />
      <line x1="5.5" y1="16" x2="7" y2="16" />
      <line x1="15" y1="7" x2="16.5" y2="7" />
      <line x1="18" y1="7" x2="19" y2="7" />
      <line x1="15" y1="11" x2="16.5" y2="11" />
      <line x1="18" y1="11" x2="19" y2="11" />
    </IconBase>
  )
);

Building2Icon.displayName = "Building2Icon";

export default Building2Icon;
