import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * BurgerIcon ("burger")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const BurgerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 9a8 5 0 0 1 16 0Z" />
      <line x1="3.5" y1="12" x2="20.5" y2="12" />
      <path d="M4 15h16v1a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3Z" />
    </IconBase>
  )
);

BurgerIcon.displayName = "BurgerIcon";

export default BurgerIcon;
