import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ButterflyIcon ("butterfly")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ButterflyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 5v14" />
      <path d="M12 8c0-3 2.5-5 5.5-5s3.5 2.5 1.5 4.5S13 9 12 8Z" />
      <path d="M12 8c0-3-2.5-5-5.5-5S3 5.5 5 7.5 11 9 12 8Z" />
      <path d="M12 13c0-2.5 2.5-4 5-4s3 2 1.5 3.8S13 14 12 13Z" />
      <path d="M12 13c0-2.5-2.5-4-5-4S4 11 5.5 12.8 11 14 12 13Z" />
    </IconBase>
  )
);

ButterflyIcon.displayName = "ButterflyIcon";

export default ButterflyIcon;
