import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CactusIcon ("cactus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CactusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M11 21V9a2 2 0 1 1 4 0v3" />
      <path d="M11 12H8a2 2 0 0 1-2-2V7" />
      <path d="M15 15h3a2 2 0 0 0 2-2V10" />
      <line x1="8" y1="21" x2="18" y2="21" />
    </IconBase>
  )
);

CactusIcon.displayName = "CactusIcon";

export default CactusIcon;
