import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CakeIcon ("cake")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CakeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="11" width="17" height="9" rx="1.5" />
      <path d="M3.5 15.5c1.5-1 3-1 4.5 0s3 1 4.5 0 3-1 4.5 0 3 1 4.5 0" />
      <line x1="8" y1="11" x2="8" y2="7.5" />
      <line x1="16" y1="11" x2="16" y2="7.5" />
      <line x1="8" y1="7" x2="8" y2="5" />
      <line x1="16" y1="7" x2="16" y2="5" />
    </IconBase>
  )
);

CakeIcon.displayName = "CakeIcon";

export default CakeIcon;
