import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CalculatorIcon ("calculator")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CalculatorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4.5" y="2.5" width="15" height="19" rx="2" />
      <line x1="7" y1="6.5" x2="17" y2="6.5" />
      <circle cx="7.5" cy="11.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="12" cy="11.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="16.5" cy="11.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="7.5" cy="15.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="12" cy="15.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="16.5" cy="15.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="7.5" cy="19" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="12" cy="19" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="16.5" cy="19" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

CalculatorIcon.displayName = "CalculatorIcon";

export default CalculatorIcon;
