import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CalendarPlusIcon ("calendar-plus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CalendarPlusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="5" width="17" height="15" rx="2" />
      <line x1="3.5" y1="10" x2="20.5" y2="10" />
      <line x1="8" y1="3" x2="8" y2="7" />
      <line x1="16" y1="3" x2="16" y2="7" />
      <line x1="12" y1="13" x2="12" y2="18" />
      <line x1="9.5" y1="15.5" x2="14.5" y2="15.5" />
    </IconBase>
  )
);

CalendarPlusIcon.displayName = "CalendarPlusIcon";

export default CalendarPlusIcon;
