import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CalendarXIcon ("calendar-x")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CalendarXIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="5" width="17" height="15" rx="2" />
      <line x1="3.5" y1="10" x2="20.5" y2="10" />
      <line x1="8" y1="3" x2="8" y2="7" />
      <line x1="16" y1="3" x2="16" y2="7" />
      <line x1="9.5" y1="13.5" x2="14.5" y2="17.5" />
      <line x1="14.5" y1="13.5" x2="9.5" y2="17.5" />
    </IconBase>
  )
);

CalendarXIcon.displayName = "CalendarXIcon";

export default CalendarXIcon;
