import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CameraIcon ("camera")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CameraIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 8.5a1 1 0 0 1 1-1h2.3l1.2-2h6l1.2 2H20a1 1 0 0 1 1 1V18a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1Z" />
      <circle cx="12" cy="13" r="3.5" />
    </IconBase>
  )
);

CameraIcon.displayName = "CameraIcon";

export default CameraIcon;
