import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CandleIcon ("candle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CandleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="9.5" y="9" width="5" height="12" rx="1" />
      <path d="M12 9c-1.5-1.5-1.5-3 0-5 1.5 2 1.5 3.5 0 5Z" />
      <line x1="12" y1="9" x2="12" y2="7" />
    </IconBase>
  )
);

CandleIcon.displayName = "CandleIcon";

export default CandleIcon;
