import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CarIcon ("car")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CarIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 16.5v-3.8L6 8h12l2 4.7v3.8" />
      <line x1="4" y1="16.5" x2="20" y2="16.5" />
      <path d="M6 8 7.5 4.5h9L18 8" />
      <circle cx="7.5" cy="16.5" r="1.7" />
      <circle cx="16.5" cy="16.5" r="1.7" />
    </IconBase>
  )
);

CarIcon.displayName = "CarIcon";

export default CarIcon;
