import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CardsIcon ("cards")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CardsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="7" width="11" height="15" rx="1.5" />
      <rect x="10" y="2" width="11" height="15" rx="1.5" />
    </IconBase>
  )
);

CardsIcon.displayName = "CardsIcon";

export default CardsIcon;
