import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CarrotIcon ("carrot")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CarrotIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9.5 14.5 19 5a2.1 2.1 0 0 1 3 3l-9.5 9.5Z" />
      <path d="M4 20l4.5-4.5" />
      <path d="M17.5 4.5c.5-1 1.5-1.5 2.5-1.5" />
      <path d="M4 20c1-3 2-4 4-4.5" />
      <path d="M4 20c3-1 4-2 4.5-4" />
    </IconBase>
  )
);

CarrotIcon.displayName = "CarrotIcon";

export default CarrotIcon;
