import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CartPlusIcon ("cart-plus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CartPlusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 4h2l2.5 12h10l2-8H7" />
      <circle cx="9.5" cy="20" r="1.3" />
      <circle cx="17" cy="20" r="1.3" />
      <line x1="17" y1="2" x2="17" y2="7" />
      <line x1="14.5" y1="4.5" x2="19.5" y2="4.5" />
    </IconBase>
  )
);

CartPlusIcon.displayName = "CartPlusIcon";

export default CartPlusIcon;
