import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CastIcon ("cast")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CastIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 8h16a2 2 0 0 1 2 2v9" />
      <path d="M2.5 12.5a6.5 6.5 0 0 1 6.5 6.5" />
      <circle cx="3.5" cy="19" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

CastIcon.displayName = "CastIcon";

export default CastIcon;
