import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CatIcon ("cat")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CatIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 9 3 4l4.5 2.5H16L20.5 4 18.5 9" />
      <path d="M5 9a7 6.5 0 0 0 14 0v1a7 6.5 0 0 1-14 0Z" />
      <circle cx="9" cy="10.5" r="0.7" fill="currentColor" stroke="none" />
      <circle cx="15" cy="10.5" r="0.7" fill="currentColor" stroke="none" />
      <path d="M11 13h2" />
    </IconBase>
  )
);

CatIcon.displayName = "CatIcon";

export default CatIcon;
