import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CaveIcon ("cave")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CaveIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2 20.5a20 10 0 0 1 20 0" />
      <path d="M7 20.5a10 6 0 0 1 10 0" />
    </IconBase>
  )
);

CaveIcon.displayName = "CaveIcon";

export default CaveIcon;
