import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CertificateIcon ("certificate")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CertificateIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="9" r="6.5" />
      <polyline points="8.8 9 10.7 11 15.2 6.5" />
      <path d="M8.5 14.5 7 21l5-2.5 5 2.5-1.5-6.5" />
    </IconBase>
  )
);

CertificateIcon.displayName = "CertificateIcon";

export default CertificateIcon;
