import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChalkboardIcon ("chalkboard")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChalkboardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="3.5" width="19" height="12" rx="1.5" />
      <line x1="9" y1="19.5" x2="15" y2="19.5" />
      <line x1="12" y1="15.5" x2="12" y2="19.5" />
      <path d="M6.5 12 10 8l2.5 2.5L17 6" />
    </IconBase>
  )
);

ChalkboardIcon.displayName = "ChalkboardIcon";

export default ChalkboardIcon;
