import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChartPieIcon ("chart-pie")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChartPieIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3.5a8.5 8.5 0 1 0 8.5 8.5H12Z" />
    </IconBase>
  )
);

ChartPieIcon.displayName = "ChartPieIcon";

export default ChartPieIcon;
