import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChartLineIcon ("chart-line")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChartLineIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 20.5h18" />
      <polyline points="4 16 9.5 10.5 13.5 14.5 20.5 6" />
    </IconBase>
  )
);

ChartLineIcon.displayName = "ChartLineIcon";

export default ChartLineIcon;
