import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChartBarIcon ("chart-bar")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChartBarIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="21" x2="4" y2="10" />
      <line x1="10" y1="21" x2="10" y2="4" />
      <line x1="16" y1="21" x2="16" y2="14" />
      <line x1="21" y1="21" x2="3" y2="21" />
    </IconBase>
  )
);

ChartBarIcon.displayName = "ChartBarIcon";

export default ChartBarIcon;
