import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CheckSquareIcon ("check-square")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CheckSquareIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="2" />
      <polyline points="8 12.5 11 15.5 16 9" />
    </IconBase>
  )
);

CheckSquareIcon.displayName = "CheckSquareIcon";

export default CheckSquareIcon;
