import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CheeseIcon ("cheese")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CheeseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 18.5 12 5l9.5 13.5Z" />
      <circle cx="14" cy="14.5" r="0.8" fill="currentColor" stroke="none" />
      <circle cx="10" cy="15.5" r="0.8" fill="currentColor" stroke="none" />
      <circle cx="12.5" cy="17.5" r="0.8" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

CheeseIcon.displayName = "CheeseIcon";

export default CheeseIcon;
