import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChefHatIcon ("chef-hat")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChefHatIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 21V13.5" />
      <path d="M17 21V13.5" />
      <path d="M6.5 21h11" />
      <path d="M6 14a4 4 0 0 1-1.5-7.7A4 4 0 0 1 12 4a4 4 0 0 1 7.5 2.3A4 4 0 0 1 18 14Z" />
    </IconBase>
  )
);

ChefHatIcon.displayName = "ChefHatIcon";

export default ChefHatIcon;
