import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChessPawnIcon ("chess-pawn")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChessPawnIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="6" r="2.5" />
      <path d="M9.5 10.5h5l1 3h-7Z" />
      <path d="M8 20 9.5 13.5h5L16 20Z" />
      <line x1="6" y1="20" x2="18" y2="20" />
    </IconBase>
  )
);

ChessPawnIcon.displayName = "ChessPawnIcon";

export default ChessPawnIcon;
