import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronsLeftIcon ("chevrons-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronsLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="16 5 10 12 16 19" />
      <polyline points="10 5 4 12 10 19" />
    </IconBase>
  )
);

ChevronsLeftIcon.displayName = "ChevronsLeftIcon";

export default ChevronsLeftIcon;
