import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronRightIcon ("chevron-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="9 5 16 12 9 19" />
    </IconBase>
  )
);

ChevronRightIcon.displayName = "ChevronRightIcon";

export default ChevronRightIcon;
