import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronLeftIcon ("chevron-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="15 5 8 12 15 19" />
    </IconBase>
  )
);

ChevronLeftIcon.displayName = "ChevronLeftIcon";

export default ChevronLeftIcon;
