import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronUpIcon ("chevron-up")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronUpIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="5 15 12 8 19 15" />
    </IconBase>
  )
);

ChevronUpIcon.displayName = "ChevronUpIcon";

export default ChevronUpIcon;
