import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronDownIcon ("chevron-down")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronDownIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="5 9 12 16 19 9" />
    </IconBase>
  )
);

ChevronDownIcon.displayName = "ChevronDownIcon";

export default ChevronDownIcon;
