import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronsRightIcon ("chevrons-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronsRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="8 5 14 12 8 19" />
      <polyline points="14 5 20 12 14 19" />
    </IconBase>
  )
);

ChevronsRightIcon.displayName = "ChevronsRightIcon";

export default ChevronsRightIcon;
