import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronsUpIcon ("chevrons-up")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronsUpIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="5 16 12 10 19 16" />
      <polyline points="5 10 12 4 19 10" />
    </IconBase>
  )
);

ChevronsUpIcon.displayName = "ChevronsUpIcon";

export default ChevronsUpIcon;
