import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ChevronsDownIcon ("chevrons-down")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ChevronsDownIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="5 8 12 14 19 8" />
      <polyline points="5 14 12 20 19 14" />
    </IconBase>
  )
);

ChevronsDownIcon.displayName = "ChevronsDownIcon";

export default ChevronsDownIcon;
