import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CircuitIcon ("circuit")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CircuitIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="6" r="2" />
      <circle cx="18" cy="6" r="2" />
      <circle cx="6" cy="18" r="2" />
      <circle cx="18" cy="18" r="2" />
      <circle cx="12" cy="12" r="2" />
      <line x1="8" y1="6" x2="16" y2="6" />
      <line x1="6" y1="8" x2="6" y2="16" />
      <line x1="18" y1="8" x2="18" y2="16" />
      <line x1="8" y1="18" x2="16" y2="18" />
      <line x1="10" y1="10.5" x2="7.5" y2="7.5" />
      <line x1="14" y1="10.5" x2="16.5" y2="7.5" />
      <line x1="10" y1="13.5" x2="7.5" y2="16.5" />
      <line x1="14" y1="13.5" x2="16.5" y2="16.5" />
    </IconBase>
  )
);

CircuitIcon.displayName = "CircuitIcon";

export default CircuitIcon;
