import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ClipboardListIcon ("clipboard-list")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ClipboardListIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4.5" y="4.5" width="15" height="17" rx="2" />
      <rect x="8.5" y="2.5" width="7" height="3" rx="1" />
      <line x1="8.5" y1="12" x2="15.5" y2="12" />
      <line x1="8.5" y1="16" x2="15.5" y2="16" />
      <circle cx="7" cy="12" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="7" cy="16" r="0.6" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

ClipboardListIcon.displayName = "ClipboardListIcon";

export default ClipboardListIcon;
