import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ClipboardCheckIcon ("clipboard-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ClipboardCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4.5" y="4.5" width="15" height="17" rx="2" />
      <rect x="8.5" y="2.5" width="7" height="3" rx="1" />
      <polyline points="8.5 13.5 10.7 15.7 15.5 10.9" />
    </IconBase>
  )
);

ClipboardCheckIcon.displayName = "ClipboardCheckIcon";

export default ClipboardCheckIcon;
