import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ClosedCaptioningIcon ("closed-captioning")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ClosedCaptioningIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="5" width="19" height="14" rx="2" />
      <path d="M9.5 10.5a2 2 0 0 0-3.5 1.3v0.4a2 2 0 0 0 3.5 1.3" />
      <path d="M17.5 10.5a2 2 0 0 0-3.5 1.3v0.4a2 2 0 0 0 3.5 1.3" />
    </IconBase>
  )
);

ClosedCaptioningIcon.displayName = "ClosedCaptioningIcon";

export default ClosedCaptioningIcon;
