import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CloudSunIcon ("cloud-sun")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CloudSunIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="8" cy="7.5" r="3" />
      <line x1="8" y1="2" x2="8" y2="3.3" />
      <line x1="3" y1="7.5" x2="4.3" y2="7.5" />
      <line x1="4" y1="3.5" x2="4.9" y2="4.4" />
      <path d="M9 19a4.5 4.5 0 0 1-.3-9 6 6 0 0 1 11.6-1.5A4.5 4.5 0 0 1 19.5 19Z" />
    </IconBase>
  )
);

CloudSunIcon.displayName = "CloudSunIcon";

export default CloudSunIcon;
