import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CloudFogIcon ("cloud-fog")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CloudFogIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 15.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 15.5Z" />
      <line x1="4" y1="19" x2="20" y2="19" />
      <line x1="6" y1="22" x2="18" y2="22" />
    </IconBase>
  )
);

CloudFogIcon.displayName = "CloudFogIcon";

export default CloudFogIcon;
