import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CloudSnowIcon ("cloud-snow")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CloudSnowIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 18.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 18.5Z" />
      <circle cx="8" cy="21" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="12" cy="21" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="16" cy="21" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

CloudSnowIcon.displayName = "CloudSnowIcon";

export default CloudSnowIcon;
