import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CloudDrizzleIcon ("cloud-drizzle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CloudDrizzleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 18.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 18.5Z" />
      <line x1="8" y1="20" x2="8" y2="21.5" />
      <line x1="12" y1="20" x2="12" y2="21.5" />
      <line x1="16" y1="20" x2="16" y2="21.5" />
    </IconBase>
  )
);

CloudDrizzleIcon.displayName = "CloudDrizzleIcon";

export default CloudDrizzleIcon;
