import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CloudLightningIcon ("cloud-lightning")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CloudLightningIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 18.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 18.5Z" />
      <polyline points="12.5 19 10 22 13 22 11 23.5" />
    </IconBase>
  )
);

CloudLightningIcon.displayName = "CloudLightningIcon";

export default CloudLightningIcon;
