import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CodeIcon ("code")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CodeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="8.5 8 4.5 12 8.5 16" />
      <polyline points="15.5 8 19.5 12 15.5 16" />
      <line x1="13.5" y1="5.5" x2="10.5" y2="18.5" />
    </IconBase>
  )
);

CodeIcon.displayName = "CodeIcon";

export default CodeIcon;
