import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CoffeeIcon ("coffee")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CoffeeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 8h11v6a5.5 5.5 0 0 1-5.5 5.5H10A5.5 5.5 0 0 1 4.5 14V8Z" />
      <path d="M16 9.5h1.5a2.5 2.5 0 0 1 0 5H16" />
      <path d="M7 3c0 1-1 1-1 2" />
      <path d="M11 3c0 1-1 1-1 2" />
    </IconBase>
  )
);

CoffeeIcon.displayName = "CoffeeIcon";

export default CoffeeIcon;
