import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CoinsIcon ("coins")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CoinsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="9" r="5.5" />
      <circle cx="16" cy="16" r="5.5" />
    </IconBase>
  )
);

CoinsIcon.displayName = "CoinsIcon";

export default CoinsIcon;
