import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CollapseIcon ("collapse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CollapseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="4 9 4 4 9 4" />
      <polyline points="20 15 20 20 15 20" />
      <line x1="4" y1="4" x2="10" y2="10" />
      <line x1="20" y1="20" x2="14" y2="14" />
    </IconBase>
  )
);

CollapseIcon.displayName = "CollapseIcon";

export default CollapseIcon;
