import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CometIcon ("comet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CometIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="16" cy="8" r="3" />
      <path d="M14 10 4 20" />
      <path d="M12.5 11.5 6 18" />
      <path d="M15 13 9.5 18.5" />
    </IconBase>
  )
);

CometIcon.displayName = "CometIcon";

export default CometIcon;
