import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CommandIcon ("command")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CommandIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="6" y="6" width="4" height="4" rx="1.5" />
      <rect x="14" y="6" width="4" height="4" rx="1.5" />
      <rect x="6" y="14" width="4" height="4" rx="1.5" />
      <rect x="14" y="14" width="4" height="4" rx="1.5" />
      <line x1="10" y1="8" x2="14" y2="8" />
      <line x1="10" y1="16" x2="14" y2="16" />
      <line x1="8" y1="10" x2="8" y2="14" />
      <line x1="16" y1="10" x2="16" y2="14" />
    </IconBase>
  )
);

CommandIcon.displayName = "CommandIcon";

export default CommandIcon;
