import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ConfettiIcon ("confetti")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ConfettiIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4" y="4" width="2.5" height="2.5" />
      <circle cx="18" cy="5" r="1.3" />
      <rect x="16" y="14" width="2.5" height="2.5" />
      <circle cx="6" cy="16" r="1.3" />
      <rect x="11" y="9" width="2.5" height="2.5" />
      <circle cx="10" cy="19" r="1.3" />
    </IconBase>
  )
);

ConfettiIcon.displayName = "ConfettiIcon";

export default ConfettiIcon;
