import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CoolIcon ("cool")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CoolIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <rect x="6.5" y="9" width="4.5" height="2.5" rx="0.8" fill="currentColor" stroke="none" />
      <rect x="13" y="9" width="4.5" height="2.5" rx="0.8" fill="currentColor" stroke="none" />
      <line x1="11" y1="10" x2="13" y2="10" />
      <path d="M8 15.5a4.5 4 0 0 0 8 0" />
    </IconBase>
  )
);

CoolIcon.displayName = "CoolIcon";

export default CoolIcon;
