import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CoralIcon ("coral")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CoralIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 21v-6" />
      <path d="M12 15c0-3 2-4 2-7s-1-4-1-4" />
      <path d="M12 15c0-4-2.5-5-2.5-8.5 0-1.5.5-2.5 1-3" />
      <path d="M12 15c1.5-2 4-2 4-5" />
      <path d="M12 15c-1.5-2-4-2-4-5" />
    </IconBase>
  )
);

CoralIcon.displayName = "CoralIcon";

export default CoralIcon;
