import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CornerUpLeftIcon ("corner-up-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CornerUpLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="9 14 4 9 9 4" />
      <path d="M4 9h11a5 5 0 0 1 5 5v6" />
    </IconBase>
  )
);

CornerUpLeftIcon.displayName = "CornerUpLeftIcon";

export default CornerUpLeftIcon;
