import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CornerDownLeftIcon ("corner-down-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CornerDownLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="9 10 4 15 9 20" />
      <path d="M4 15h11a5 5 0 0 0 5-5V4" />
    </IconBase>
  )
);

CornerDownLeftIcon.displayName = "CornerDownLeftIcon";

export default CornerDownLeftIcon;
