import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CornerUpRightIcon ("corner-up-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CornerUpRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="15 14 20 9 15 4" />
      <path d="M20 9H9a5 5 0 0 0-5 5v6" />
    </IconBase>
  )
);

CornerUpRightIcon.displayName = "CornerUpRightIcon";

export default CornerUpRightIcon;
