import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CornIcon ("corn")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CornIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5c6 0 8 5 8 10s-3.5 7-8 7-4-6-4-10 1.5-7 4-7Z" />
      <line x1="8" y1="6.5" x2="11.5" y2="7" />
      <line x1="7" y1="9.5" x2="11" y2="10" />
      <line x1="6.7" y1="12.5" x2="11" y2="13" />
      <line x1="7" y1="15.5" x2="10.5" y2="16" />
      <path d="M8 3.5c1-1.5 2.5-2 4-1.5" />
    </IconBase>
  )
);

CornIcon.displayName = "CornIcon";

export default CornIcon;
