import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CornerDownRightIcon ("corner-down-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CornerDownRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="15 10 20 15 15 20" />
      <path d="M20 15H9a5 5 0 0 1-5-5V4" />
    </IconBase>
  )
);

CornerDownRightIcon.displayName = "CornerDownRightIcon";

export default CornerDownRightIcon;
