import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CpuIcon ("cpu")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CpuIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="6.5" y="6.5" width="11" height="11" rx="1.5" />
      <rect x="10" y="10" width="4" height="4" />
      <line x1="9" y1="2.5" x2="9" y2="6.5" />
      <line x1="15" y1="2.5" x2="15" y2="6.5" />
      <line x1="9" y1="17.5" x2="9" y2="21.5" />
      <line x1="15" y1="17.5" x2="15" y2="21.5" />
      <line x1="2.5" y1="9" x2="6.5" y2="9" />
      <line x1="2.5" y1="15" x2="6.5" y2="15" />
      <line x1="17.5" y1="9" x2="21.5" y2="9" />
      <line x1="17.5" y1="15" x2="21.5" y2="15" />
    </IconBase>
  )
);

CpuIcon.displayName = "CpuIcon";

export default CpuIcon;
