import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CropIcon ("crop")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CropIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 2.5v14a1.5 1.5 0 0 0 1.5 1.5H21.5" />
      <path d="M18 21.5v-14a1.5 1.5 0 0 0-1.5-1.5H2.5" />
    </IconBase>
  )
);

CropIcon.displayName = "CropIcon";

export default CropIcon;
