import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CrossShapeIcon ("cross-shape")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CrossShapeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6Z" />
    </IconBase>
  )
);

CrossShapeIcon.displayName = "CrossShapeIcon";

export default CrossShapeIcon;
