import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CrossMedicalIcon ("cross-medical")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CrossMedicalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M10 3h4v6h6v4h-6v8h-4v-8H4V9h6Z" />
    </IconBase>
  )
);

CrossMedicalIcon.displayName = "CrossMedicalIcon";

export default CrossMedicalIcon;
