import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CrownIcon ("crown")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CrownIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 8 7 12 12 5 17 12 21 8 19 18H5Z" />
      <line x1="5" y1="18" x2="19" y2="18" />
    </IconBase>
  )
);

CrownIcon.displayName = "CrownIcon";

export default CrownIcon;
