import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CupIcon ("cup")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CupIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3h9l-1 13a3 3 0 0 1-3 2.7h-1A3 3 0 0 1 7 16Z" />
      <line x1="4" y1="3" x2="17" y2="3" />
    </IconBase>
  )
);

CupIcon.displayName = "CupIcon";

export default CupIcon;
