import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * CuttingBoardIcon ("cutting-board")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const CuttingBoardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="4" width="18" height="14" rx="2" />
      <circle cx="18" cy="19" r="1.3" />
      <line x1="7" y1="8" x2="12" y2="8" />
      <line x1="7" y1="12" x2="10" y2="12" />
    </IconBase>
  )
);

CuttingBoardIcon.displayName = "CuttingBoardIcon";

export default CuttingBoardIcon;
