import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DesertIcon ("desert")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DesertIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2 20 6.5 10a2 2 0 0 1 3.6 0L12 14l1-2a2 2 0 0 1 3.6 0L20 20Z" />
      <circle cx="18.5" cy="5.5" r="2.3" />
    </IconBase>
  )
);

DesertIcon.displayName = "DesertIcon";

export default DesertIcon;
