import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DiamondIcon ("diamond")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DiamondIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 20 12 12 21 4 12Z" />
    </IconBase>
  )
);

DiamondIcon.displayName = "DiamondIcon";

export default DiamondIcon;
