import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DirectionsIcon ("directions")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DirectionsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5 20 12l-8 9.5L4 12Z" />
      <line x1="8" y1="12" x2="16" y2="12" />
      <polyline points="13 9 16 12 13 15" />
    </IconBase>
  )
);

DirectionsIcon.displayName = "DirectionsIcon";

export default DirectionsIcon;
