import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DivideIcon ("divide")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DivideIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="6.5" r="1.3" fill="currentColor" stroke="none" />
      <line x1="5" y1="12" x2="19" y2="12" />
      <circle cx="12" cy="17.5" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

DivideIcon.displayName = "DivideIcon";

export default DivideIcon;
