import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DnaIcon ("dna")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DnaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3c0 6 12 6 12 12" />
      <path d="M18 21c0-6-12-6-12-12" />
      <line x1="7.5" y1="6" x2="16.5" y2="6" />
      <line x1="6.5" y1="10" x2="17.5" y2="10" />
      <line x1="6.5" y1="14" x2="17.5" y2="14" />
      <line x1="7.5" y1="18" x2="16.5" y2="18" />
    </IconBase>
  )
);

DnaIcon.displayName = "DnaIcon";

export default DnaIcon;
