import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DogIcon ("dog")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DogIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 9c0-2.5 1.5-4.5 3.5-4.5S10 6 10 8" />
      <path d="M20 9c0-2.5-1.5-4.5-3.5-4.5S13 6 13 8" />
      <path d="M5 10a7 6.5 0 0 0 14 0v1.5a7 6.5 0 0 1-14 0Z" />
      <circle cx="9.5" cy="11.5" r="0.7" fill="currentColor" stroke="none" />
      <circle cx="14.5" cy="11.5" r="0.7" fill="currentColor" stroke="none" />
      <path d="M11 14.5h2" />
    </IconBase>
  )
);

DogIcon.displayName = "DogIcon";

export default DogIcon;
