import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DollarSignIcon ("dollar-sign")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DollarSignIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="2.5" x2="12" y2="21.5" />
      <path d="M16.5 6.5a4 3 0 0 0-4-2 4 3 0 0 0 0 6 4 3 0 0 1 0 6 4 3 0 0 1-4-2" />
    </IconBase>
  )
);

DollarSignIcon.displayName = "DollarSignIcon";

export default DollarSignIcon;
