import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DownloadCloudIcon ("download-cloud")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DownloadCloudIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 15.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 15.5H14" />
      <polyline points="9.5 18 12 20.5 14.5 18" />
      <line x1="12" y1="12" x2="12" y2="20.5" />
    </IconBase>
  )
);

DownloadCloudIcon.displayName = "DownloadCloudIcon";

export default DownloadCloudIcon;
