import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * DumbbellIcon ("dumbbell")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const DumbbellIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="10" width="3" height="4" rx="1" />
      <rect x="18.5" y="10" width="3" height="4" rx="1" />
      <line x1="7" y1="12" x2="17" y2="12" />
      <rect x="5.5" y="8" width="2" height="8" rx="1" />
      <rect x="16.5" y="8" width="2" height="8" rx="1" />
    </IconBase>
  )
);

DumbbellIcon.displayName = "DumbbellIcon";

export default DumbbellIcon;
