import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EarIcon ("ear")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EarIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 13a5 5 0 0 1 5-8.5A6.5 6.5 0 0 1 19 11c0 3-2 4-2 6.5a2.5 2.5 0 0 1-5 0v-2a2 2 0 0 0-4 0" />
    </IconBase>
  )
);

EarIcon.displayName = "EarIcon";

export default EarIcon;
