import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EclipseIcon ("eclipse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EclipseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9.5" cy="12" r="7" />
      <circle cx="14.5" cy="12" r="7" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

EclipseIcon.displayName = "EclipseIcon";

export default EclipseIcon;
