import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EggIcon ("egg")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EggIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 21.5a6.5 5.5 0 0 0 6.5-5.5C18.5 10 15 3 12 3S5.5 10 5.5 16a6.5 5.5 0 0 0 6.5 5.5Z" />
    </IconBase>
  )
);

EggIcon.displayName = "EggIcon";

export default EggIcon;
