import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EraserIcon ("eraser")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EraserIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 20.5H4.5L2.5 18l11-11 6.5 6.5-8 8Z" />
      <line x1="8" y1="20.5" x2="14" y2="14.5" />
    </IconBase>
  )
);

EraserIcon.displayName = "EraserIcon";

export default EraserIcon;
