import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EuroSignIcon ("euro-sign")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EuroSignIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M17 5.5a7 7 0 1 0 0 13" />
      <line x1="4" y1="10" x2="15" y2="10" />
      <line x1="4" y1="14" x2="13.5" y2="14" />
    </IconBase>
  )
);

EuroSignIcon.displayName = "EuroSignIcon";

export default EuroSignIcon;
