import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ExchangeIcon ("exchange")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ExchangeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 7h13" />
      <polyline points="14 3.5 17 7 14 10.5" />
      <path d="M20 17H7" />
      <polyline points="10 13.5 7 17 10 20.5" />
    </IconBase>
  )
);

ExchangeIcon.displayName = "ExchangeIcon";

export default ExchangeIcon;
