import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ExclamationIcon ("exclamation")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ExclamationIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="4" x2="12" y2="14" />
      <circle cx="12" cy="19" r="1.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

ExclamationIcon.displayName = "ExclamationIcon";

export default ExclamationIcon;
