import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ExportIcon ("export")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ExportIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="5" width="12" height="14" rx="1.5" />
      <polyline points="15 9 20 12 15 15" />
      <line x1="20" y1="12" x2="9" y2="12" />
    </IconBase>
  )
);

ExportIcon.displayName = "ExportIcon";

export default ExportIcon;
