import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ExternalLinkIcon ("external-link")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ExternalLinkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M18 13.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5.5" />
      <polyline points="14.5 3 21 3 21 9.5" />
      <line x1="10.5" y1="13.5" x2="21" y2="3" />
    </IconBase>
  )
);

ExternalLinkIcon.displayName = "ExternalLinkIcon";

export default ExternalLinkIcon;
