import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EyedropperIcon ("eyedropper")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EyedropperIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M15 5 19 9l-9 9-4.5 1.5L7 15Z" />
      <line x1="4" y1="20.5" x2="7" y2="17.5" />
      <line x1="13" y1="3" x2="17" y2="7" />
    </IconBase>
  )
);

EyedropperIcon.displayName = "EyedropperIcon";

export default EyedropperIcon;
