import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * EyeOffIcon ("eye-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const EyeOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12Z" />
      <circle cx="12" cy="12" r="3" />
      <line x1="4" y1="4" x2="20" y2="20" />
    </IconBase>
  )
);

EyeOffIcon.displayName = "EyeOffIcon";

export default EyeOffIcon;
