import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FactoryIcon ("factory")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FactoryIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 20.5V11l5 3.5V11l5 3.5V11l5 3.5V6h2.5v14.5Z" />
      <line x1="3" y1="20.5" x2="21" y2="20.5" />
    </IconBase>
  )
);

FactoryIcon.displayName = "FactoryIcon";

export default FactoryIcon;
