import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FaucetIcon ("faucet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FaucetIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3v6" />
      <path d="M6 9h9a3 3 0 0 1 3 3v1" />
      <line x1="18" y1="13" x2="18" y2="16" />
      <path d="M6 9a4 4 0 0 0-3 3.9V15" />
      <line x1="6" y1="15" x2="6" y2="19" />
    </IconBase>
  )
);

FaucetIcon.displayName = "FaucetIcon";

export default FaucetIcon;
