import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FeatherIcon ("feather")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FeatherIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M20.5 3.5c-6 0-14 4-16 12-1 4 1.5 6 5 5 8-2 12-10 12-16Z" />
      <line x1="4.5" y1="20.5" x2="14.5" y2="10.5" />
      <line x1="9" y1="14" x2="12.5" y2="17.5" />
    </IconBase>
  )
);

FeatherIcon.displayName = "FeatherIcon";

export default FeatherIcon;
