import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FilesIcon ("files")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FilesIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 6.5h7l3 3V20a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V7.5a1 1 0 0 1 1-1Z" />
      <path d="M6 3.5h7l3 3" />
      <path d="M6 3.5a1 1 0 0 0-1 1V17" />
    </IconBase>
  )
);

FilesIcon.displayName = "FilesIcon";

export default FilesIcon;
