import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FileCheckIcon ("file-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FileCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3.5h7l4 4V20a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1Z" />
      <polyline points="14 3.5 14 7.5 18 7.5" />
      <polyline points="9.5 14.5 11.3 16.3 14.5 12.7" />
    </IconBase>
  )
);

FileCheckIcon.displayName = "FileCheckIcon";

export default FileCheckIcon;
