import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FileXIcon ("file-x")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FileXIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3.5h7l4 4V20a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1Z" />
      <polyline points="14 3.5 14 7.5 18 7.5" />
      <line x1="10" y1="12.5" x2="14" y2="16.5" />
      <line x1="14" y1="12.5" x2="10" y2="16.5" />
    </IconBase>
  )
);

FileXIcon.displayName = "FileXIcon";

export default FileXIcon;
