import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FilterIcon ("filter")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FilterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 4.5h17L14 12.5V19l-4 2v-8.5Z" />
    </IconBase>
  )
);

FilterIcon.displayName = "FilterIcon";

export default FilterIcon;
