import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FilterXIcon ("filter-x")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FilterXIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 4.5h13L11.5 11v8l-3 1.5v-9.2Z" />
      <line x1="16" y1="6" x2="21" y2="11" />
      <line x1="21" y1="6" x2="16" y2="11" />
    </IconBase>
  )
);

FilterXIcon.displayName = "FilterXIcon";

export default FilterXIcon;
