import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FingerprintIcon ("fingerprint")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FingerprintIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3.5a8.5 8.5 0 0 0-8.5 8.5c0 2.5.5 4 1.5 6" />
      <path d="M12 3.5a8.5 8.5 0 0 1 8.5 8.5c0 1.2-.1 2.2-.3 3.2" />
      <path d="M12 7.5a4.5 4.5 0 0 0-4.5 4.5c0 4-1 6-2 7.5" />
      <path d="M12 7.5a4.5 4.5 0 0 1 4.5 4.5c0 2 .2 3.5.7 4.8" />
      <path d="M12 11.5a1 1 0 0 0-1 1c0 3.5-.5 6-2 8" />
      <path d="M16 20a13 13 0 0 0 1-4.5" />
    </IconBase>
  )
);

FingerprintIcon.displayName = "FingerprintIcon";

export default FingerprintIcon;
