import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FireworkIcon ("firework")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FireworkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="3" x2="12" y2="8" />
      <line x1="12" y1="16" x2="12" y2="21" />
      <line x1="3" y1="12" x2="8" y2="12" />
      <line x1="16" y1="12" x2="21" y2="12" />
      <line x1="5.5" y1="5.5" x2="9" y2="9" />
      <line x1="18.5" y1="5.5" x2="15" y2="9" />
      <line x1="5.5" y1="18.5" x2="9" y2="15" />
      <line x1="18.5" y1="18.5" x2="15" y2="15" />
      <circle cx="12" cy="12" r="2" />
    </IconBase>
  )
);

FireworkIcon.displayName = "FireworkIcon";

export default FireworkIcon;
