import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FireTruckIcon ("fire-truck")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FireTruckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="8" width="14" height="9" rx="1" />
      <path d="M16.5 11h3l2.5 2.5v3.5h-5.5Z" />
      <circle cx="7" cy="19.5" r="1.7" />
      <circle cx="17.5" cy="19.5" r="1.7" />
      <line x1="6" y1="4.5" x2="10" y2="4.5" />
      <line x1="8" y1="4.5" x2="8" y2="8" />
    </IconBase>
  )
);

FireTruckIcon.displayName = "FireTruckIcon";

export default FireTruckIcon;
