import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FishIcon ("fish")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FishIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 12c3-4 8-6 12-4 2 1 4 3 6 4-2 1-4 3-6 4-4 2-9 0-12-4Z" />
      <circle cx="15" cy="10.5" r="0.7" fill="currentColor" stroke="none" />
      <path d="M3 12 1 9m2 3-2 3" />
    </IconBase>
  )
);

FishIcon.displayName = "FishIcon";

export default FishIcon;
