import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FlagIcon ("flag")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FlagIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 21V4" />
      <path d="M5 4h13l-3 4.5L18 13H5Z" />
    </IconBase>
  )
);

FlagIcon.displayName = "FlagIcon";

export default FlagIcon;
