import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FlagCheckeredIcon ("flag-checkered")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FlagCheckeredIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="5" y1="21" x2="5" y2="3" />
      <path d="M5 4h14v10H5Z" />
      <rect x="5" y="4" width="3.5" height="3.3" fill="currentColor" stroke="none" />
      <rect x="12" y="4" width="3.5" height="3.3" fill="currentColor" stroke="none" />
      <rect x="8.5" y="7.3" width="3.5" height="3.3" fill="currentColor" stroke="none" />
      <rect x="15.5" y="7.3" width="3.5" height="3.3" fill="currentColor" stroke="none" />
      <rect x="5" y="10.6" width="3.5" height="3.3" fill="currentColor" stroke="none" />
      <rect x="12" y="10.6" width="3.5" height="3.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

FlagCheckeredIcon.displayName = "FlagCheckeredIcon";

export default FlagCheckeredIcon;
