import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FlameIcon ("flame")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FlameIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5s5.5 5 5.5 10a5.5 5.5 0 1 1-11 0c0-1.4.6-2.6 1.3-3.6.2 1 .9 1.6 1.7 1.6.9 0 1.5-1 1-2A6 6 0 0 1 12 2.5Z" />
    </IconBase>
  )
);

FlameIcon.displayName = "FlameIcon";

export default FlameIcon;
