import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FloppyDiskIcon ("floppy-disk")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FloppyDiskIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4.5 3.5h13l3 3V19.5a1 1 0 0 1-1 1H4.5a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1Z" />
      <rect x="7" y="3.5" width="8" height="6" />
      <rect x="7" y="14" width="10" height="6.5" />
    </IconBase>
  )
);

FloppyDiskIcon.displayName = "FloppyDiskIcon";

export default FloppyDiskIcon;
