import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FolderOpenIcon ("folder-open")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FolderOpenIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 8V6.5a1 1 0 0 1 1-1H10l2 2h7a1 1 0 0 1 1 1v1" />
      <path d="M2.7 9.5h17.6a1 1 0 0 1 1 1.2l-1.4 7A1 1 0 0 1 19 18.5H4a1 1 0 0 1-1-.8l-1.3-7a1 1 0 0 1 1-1.2Z" />
    </IconBase>
  )
);

FolderOpenIcon.displayName = "FolderOpenIcon";

export default FolderOpenIcon;
