import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FootprintsIcon ("footprints")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FootprintsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 4a2 2.5 0 1 0 0 5 2 2.5 0 0 0 0-5Z" />
      <path d="M5 11a2 3 0 1 0 0 6 2 3 0 0 0 0-6Z" />
      <path d="M17 8a2 2.5 0 1 0 0 5 2 2.5 0 0 0 0-5Z" />
      <path d="M17 15a2 3 0 1 0 0 6 2 3 0 0 0 0-6Z" />
    </IconBase>
  )
);

FootprintsIcon.displayName = "FootprintsIcon";

export default FootprintsIcon;
