import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FootballIcon ("football")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FootballIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <polygon points="12 8 15 10.5 14 14 10 14 9 10.5" />
      <line x1="12" y1="8" x2="12" y2="3.5" />
      <line x1="15" y1="10.5" x2="19.5" y2="9" />
      <line x1="14" y1="14" x2="16" y2="19" />
      <line x1="10" y1="14" x2="8" y2="19" />
      <line x1="9" y1="10.5" x2="4.5" y2="9" />
    </IconBase>
  )
);

FootballIcon.displayName = "FootballIcon";

export default FootballIcon;
