import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ForestIcon ("forest")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ForestIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3 3 11h2.5l-3 5h3v4h3v-4h3l-3-5h2.5Z" />
      <path d="M16 6 12.5 13h2l-2.5 4.5h2v3.5h3v-3.5h2L17 13h2Z" />
    </IconBase>
  )
);

ForestIcon.displayName = "ForestIcon";

export default ForestIcon;
