import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ForkliftIcon ("forklift")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ForkliftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="12" width="7" height="6" rx="1" />
      <circle cx="5" cy="19.5" r="1.5" />
      <line x1="10" y1="8" x2="10" y2="18" />
      <line x1="10" y1="8" x2="17" y2="8" />
      <line x1="17" y1="8" x2="17" y2="14" />
      <rect x="15" y="12" width="4" height="6" rx="1" />
      <circle cx="18" cy="19.5" r="1.5" />
    </IconBase>
  )
);

ForkliftIcon.displayName = "ForkliftIcon";

export default ForkliftIcon;
