import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ForwardIcon ("forward")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ForwardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 8.5h9a5 5 0 0 1 5 5V17" />
      <polyline points="9 4 13 8.5 9 13" />
    </IconBase>
  )
);

ForwardIcon.displayName = "ForwardIcon";

export default ForwardIcon;
