import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FridgeIcon ("fridge")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FridgeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="5" y="2.5" width="14" height="19" rx="1.5" />
      <line x1="5" y1="9.5" x2="19" y2="9.5" />
      <line x1="8" y1="5" x2="8" y2="7" />
      <line x1="8" y1="12" x2="8" y2="14" />
    </IconBase>
  )
);

FridgeIcon.displayName = "FridgeIcon";

export default FridgeIcon;
