import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FuelIcon ("fuel")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FuelIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="4" width="10" height="16" rx="1" />
      <line x1="3.5" y1="9" x2="13.5" y2="9" />
      <path d="M13.5 9h3l3 3v6a1.5 1.5 0 0 1-3 0v-2.5a1.5 1.5 0 0 0-1.5-1.5h-1.5" />
    </IconBase>
  )
);

FuelIcon.displayName = "FuelIcon";

export default FuelIcon;
