import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * FunctionSquareIcon ("function-square")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const FunctionSquareIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="2" />
      <path d="M10.5 8.5h-1a1.5 1.5 0 0 0-1.5 1.5v6.5" />
      <line x1="7" y1="12.5" x2="10" y2="12.5" />
    </IconBase>
  )
);

FunctionSquareIcon.displayName = "FunctionSquareIcon";

export default FunctionSquareIcon;
