import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GamepadIcon ("gamepad")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GamepadIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 8h10a4 4 0 0 1 4 4.5l-.5 3A2.5 2.5 0 0 1 18 17.5c-1 0-1.5-.5-2.5-1.5l-1-1h-5l-1 1c-1 1-1.5 1.5-2.5 1.5a2.5 2.5 0 0 1-2.5-2L3 12.5A4 4 0 0 1 7 8Z" />
      <line x1="7.5" y1="12" x2="10.5" y2="12" />
      <line x1="9" y1="10.5" x2="9" y2="13.5" />
      <circle cx="15" cy="11" r="0.8" fill="currentColor" stroke="none" />
      <circle cx="17" cy="13" r="0.8" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

GamepadIcon.displayName = "GamepadIcon";

export default GamepadIcon;
