import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GaugeIcon ("gauge")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GaugeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 16a8 8 0 1 1 16 0" />
      <line x1="12" y1="16" x2="16" y2="10" />
      <circle cx="12" cy="16" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

GaugeIcon.displayName = "GaugeIcon";

export default GaugeIcon;
