import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GemIcon ("gem")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GemIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3h12l3 6-9 12L3 9Z" />
      <path d="M3 9h18" />
      <path d="M9 3 12 9l-3.5 12" />
      <path d="M15 3 12 9l3.5 12" />
    </IconBase>
  )
);

GemIcon.displayName = "GemIcon";

export default GemIcon;
