import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GiftIcon ("gift")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GiftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="8.5" width="17" height="12" rx="1" />
      <line x1="3.5" y1="13" x2="20.5" y2="13" />
      <line x1="12" y1="8.5" x2="12" y2="20.5" />
      <path d="M12 8.5c-1-2.5-2.5-4-4-4-1.2 0-2 1-1.3 2.3.6 1.1 2.3 1.7 5.3 1.7Z" />
      <path d="M12 8.5c1-2.5 2.5-4 4-4 1.2 0 2 1 1.3 2.3-.6 1.1-2.3 1.7-5.3 1.7Z" />
    </IconBase>
  )
);

GiftIcon.displayName = "GiftIcon";

export default GiftIcon;
