import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GitBranchIcon ("git-branch")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GitBranchIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="5" r="2" />
      <circle cx="6" cy="19" r="2" />
      <circle cx="18" cy="15" r="2" />
      <line x1="6" y1="7" x2="6" y2="17" />
      <path d="M6 10a8 8 0 0 0 8.5 6.2" />
    </IconBase>
  )
);

GitBranchIcon.displayName = "GitBranchIcon";

export default GitBranchIcon;
