import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GitCommitIcon ("git-commit")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GitCommitIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="3" />
      <line x1="2.5" y1="12" x2="9" y2="12" />
      <line x1="15" y1="12" x2="21.5" y2="12" />
    </IconBase>
  )
);

GitCommitIcon.displayName = "GitCommitIcon";

export default GitCommitIcon;
