import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GitPullRequestIcon ("git-pull-request")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GitPullRequestIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="6" r="2" />
      <circle cx="6" cy="18" r="2" />
      <circle cx="18" cy="6" r="2" />
      <line x1="6" y1="8" x2="6" y2="16" />
      <path d="M18 8v4a4 4 0 0 1-4 4h-2" />
      <polyline points="14.5 13.5 12 16 14.5 18.5" />
    </IconBase>
  )
);

GitPullRequestIcon.displayName = "GitPullRequestIcon";

export default GitPullRequestIcon;
