import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GlassesIcon ("glasses")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GlassesIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6.5" cy="14.5" r="3.5" />
      <circle cx="17.5" cy="14.5" r="3.5" />
      <path d="M10 14.5h4" />
      <path d="M3 14.5 2 9" />
      <path d="M21 14.5 22 9" />
    </IconBase>
  )
);

GlassesIcon.displayName = "GlassesIcon";

export default GlassesIcon;
