import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GraduationCapIcon ("graduation-cap")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GraduationCapIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2 9 12 4l10 5-10 5Z" />
      <path d="M6 11.5V17c0 1.5 2.5 3 6 3s6-1.5 6-3v-5.5" />
      <path d="M22 9v6" />
    </IconBase>
  )
);

GraduationCapIcon.displayName = "GraduationCapIcon";

export default GraduationCapIcon;
