import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * GrapeIcon ("grape")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const GrapeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="9" r="2.2" />
      <circle cx="13" cy="9" r="2.2" />
      <circle cx="7" cy="13" r="2.2" />
      <circle cx="11" cy="13" r="2.2" />
      <circle cx="15" cy="13" r="2.2" />
      <circle cx="9" cy="17" r="2.2" />
      <circle cx="13" cy="17" r="2.2" />
      <path d="M11 4.5v2.5" />
      <path d="M11 4.5c0-1 1-1.5 2-1.5" />
    </IconBase>
  )
);

GrapeIcon.displayName = "GrapeIcon";

export default GrapeIcon;
