import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HailIcon ("hail")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HailIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 12.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 12.5Z" />
      <circle cx="8.5" cy="17" r="1" />
      <circle cx="12" cy="19" r="1" />
      <circle cx="15.5" cy="17" r="1" />
    </IconBase>
  )
);

HailIcon.displayName = "HailIcon";

export default HailIcon;
