import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HammerIcon ("hammer")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HammerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M14 7 18 3l3 3-4 4Z" />
      <path d="M15.5 8.5 5.5 18.5a2 2 0 0 1-2.8-2.8L12.7 5.7Z" />
    </IconBase>
  )
);

HammerIcon.displayName = "HammerIcon";

export default HammerIcon;
