import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HandIcon ("hand")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HandIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 12.5V5a1.5 1.5 0 0 1 3 0v6" />
      <path d="M12 11V4a1.5 1.5 0 0 1 3 0v7" />
      <path d="M15 11.5V6a1.5 1.5 0 0 1 3 0v8" />
      <path d="M6 12v-2a1.5 1.5 0 0 1 3 0v3" />
      <path d="M6 13c0 5 2.5 8 7 8s6-3 6-6.5v-2" />
    </IconBase>
  )
);

HandIcon.displayName = "HandIcon";

export default HandIcon;
