import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HandRaisedIcon ("hand-raised")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HandRaisedIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 11V5a1.5 1.5 0 0 1 3 0v6" />
      <path d="M12 10.5V4a1.5 1.5 0 0 1 3 0v7" />
      <path d="M15 11V6.5a1.5 1.5 0 0 1 3 0v7.5" />
      <path d="M6 13v-1.5a1.5 1.5 0 0 1 3 0V13" />
      <path d="M6 13.5c0 4.5 2.5 7 7 7s6-2.5 6-6v-3" />
    </IconBase>
  )
);

HandRaisedIcon.displayName = "HandRaisedIcon";

export default HandRaisedIcon;
