import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HandshakeIcon ("handshake")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HandshakeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 12 6 8.5l3 2.5" />
      <path d="M21.5 12 18 8.5l-3 2.5" />
      <path d="M9 11 12 13.5 15 11" />
      <path d="M6 8.5l3.5 3a1.5 1.5 0 0 0 2 0l.5-.5a1.5 1.5 0 0 1 2 0l.5.5a1.5 1.5 0 0 0 2 0l3.5-3" />
    </IconBase>
  )
);

HandshakeIcon.displayName = "HandshakeIcon";

export default HandshakeIcon;
