import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HardDriveIcon ("hard-drive")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HardDriveIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="2.5" y1="12.5" x2="21.5" y2="12.5" />
      <path d="M5.5 4.5h13l3 8v6a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1v-6Z" />
      <circle cx="7" cy="16.5" r="0.9" fill="currentColor" stroke="none" />
      <circle cx="11" cy="16.5" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

HardDriveIcon.displayName = "HardDriveIcon";

export default HardDriveIcon;
