import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HashIcon ("hash")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HashIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="9" y1="3.5" x2="6.5" y2="20.5" />
      <line x1="17.5" y1="3.5" x2="15" y2="20.5" />
      <line x1="4" y1="9" x2="20" y2="9" />
      <line x1="3.3" y1="15" x2="19.3" y2="15" />
    </IconBase>
  )
);

HashIcon.displayName = "HashIcon";

export default HashIcon;
