import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HatIcon ("hat")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HatIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 15 12 4l8 11Z" />
      <path d="M2 15h20l-1.5 3h-17Z" />
    </IconBase>
  )
);

HatIcon.displayName = "HatIcon";

export default HatIcon;
