import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HeadingIcon ("heading")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HeadingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="5" y1="4.5" x2="5" y2="19.5" />
      <line x1="17" y1="4.5" x2="17" y2="19.5" />
      <line x1="5" y1="12" x2="17" y2="12" />
    </IconBase>
  )
);

HeadingIcon.displayName = "HeadingIcon";

export default HeadingIcon;
