import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HeartPulseIcon ("heart-pulse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HeartPulseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 19.5 4 12.3a5 5 0 0 1 7-7.2L12 6l1-.9a5 5 0 0 1 7 7.2Z" />
      <polyline points="7 12 9.5 12 11 9 13 15 14.5 12 17 12" />
    </IconBase>
  )
);

HeartPulseIcon.displayName = "HeartPulseIcon";

export default HeartPulseIcon;
