import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HeartIcon ("heart")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HeartIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 20.5 4.8 13.4a4.8 4.8 0 0 1 6.8-6.8L12 7l.4-.4a4.8 4.8 0 0 1 6.8 6.8Z" />
    </IconBase>
  )
);

HeartIcon.displayName = "HeartIcon";

export default HeartIcon;
