import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HelicopterIcon ("helicopter")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HelicopterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="4" x2="20" y2="4" />
      <line x1="12" y1="4" x2="12" y2="6.5" />
      <path d="M6 15a6 4.5 0 0 1 12 0Z" />
      <line x1="18" y1="15" x2="22" y2="14" />
      <line x1="6" y1="19" x2="18" y2="19" />
    </IconBase>
  )
);

HelicopterIcon.displayName = "HelicopterIcon";

export default HelicopterIcon;
