import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HelpCircleIcon ("help-circle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HelpCircleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <path d="M9.2 9.5a2.8 2.8 0 1 1 4.3 2.4c-.9.6-1.5 1.1-1.5 2.1" />
      <circle cx="12" cy="17.2" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

HelpCircleIcon.displayName = "HelpCircleIcon";

export default HelpCircleIcon;
