import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HexagonIcon ("hexagon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HexagonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5h8L21 12l-5 8.5H8L3 12Z" />
    </IconBase>
  )
);

HexagonIcon.displayName = "HexagonIcon";

export default HexagonIcon;
