import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HighlighterIcon ("highlighter")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HighlighterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M15 3.5 20.5 9 10 19.5 4.5 21 6 15.5Z" />
      <line x1="12.5" y1="6" x2="18" y2="11.5" />
    </IconBase>
  )
);

HighlighterIcon.displayName = "HighlighterIcon";

export default HighlighterIcon;
