import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HoneyIcon ("honey")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HoneyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5h8v3l-2 2v4l2 2v3l-2 2H10l-2-2v-3l2-2v-4l-2-2Z" />
      <line x1="8" y1="9" x2="16" y2="9" />
      <line x1="8" y1="15" x2="16" y2="15" />
    </IconBase>
  )
);

HoneyIcon.displayName = "HoneyIcon";

export default HoneyIcon;
