import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HourglassIcon ("hourglass")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HourglassIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3h12" />
      <path d="M6 21h12" />
      <path d="M7 3v3.5a5 5 0 0 0 5 5 5 5 0 0 0 5-5V3" />
      <path d="M7 21v-3.5a5 5 0 0 1 5-5 5 5 0 0 1 5 5V21" />
    </IconBase>
  )
);

HourglassIcon.displayName = "HourglassIcon";

export default HourglassIcon;
