import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * HurricaneIcon ("hurricane")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const HurricaneIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <path d="M12 3a9 5 0 0 1 6 8" />
      <path d="M12 21a9 5 0 0 1-6-8" />
      <circle cx="12" cy="12" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

HurricaneIcon.displayName = "HurricaneIcon";

export default HurricaneIcon;
