import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * IcebergIcon ("iceberg")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const IcebergIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 15.5 9 5l3 5 2-3 6 8.5Z" />
      <line x1="2" y1="15.5" x2="22" y2="15.5" />
      <path d="M9 5 6.5 12" stroke-dasharray="1.5 1.5" />
    </IconBase>
  )
);

IcebergIcon.displayName = "IcebergIcon";

export default IcebergIcon;
