import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * IceCreamIcon ("ice-cream")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const IceCreamIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 10a5.5 5.5 0 0 1 11 0Z" />
      <path d="M6.5 10 12 21.5 17.5 10Z" />
    </IconBase>
  )
);

IceCreamIcon.displayName = "IceCreamIcon";

export default IceCreamIcon;
