import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ImportIcon ("import")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ImportIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="9" y="5" width="12" height="14" rx="1.5" />
      <polyline points="9 9 4 12 9 15" />
      <line x1="4" y1="12" x2="15" y2="12" />
    </IconBase>
  )
);

ImportIcon.displayName = "ImportIcon";

export default ImportIcon;
