import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * InfinityIcon ("infinity")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const InfinityIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 15a4 4 0 1 1 0-6c2.5 0 3.5 2 5 3s2.5 3 5 3a4 4 0 1 0 0-6c-2.5 0-3.5 2-5 3s-2.5 3-5 3Z" />
    </IconBase>
  )
);

InfinityIcon.displayName = "InfinityIcon";

export default InfinityIcon;
