import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * InvoiceIcon ("invoice")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const InvoiceIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3.5h10l3 3V21H7Z" />
      <line x1="17" y1="3.5" x2="17" y2="6.5" />
      <line x1="20" y1="6.5" x2="17" y2="6.5" />
      <line x1="9.5" y1="11" x2="15.5" y2="11" />
      <line x1="9.5" y1="14.5" x2="15.5" y2="14.5" />
      <line x1="9.5" y1="18" x2="13" y2="18" />
    </IconBase>
  )
);

InvoiceIcon.displayName = "InvoiceIcon";

export default InvoiceIcon;
