import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * IslandIcon ("island")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const IslandIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 18a20 5 0 0 0 16 0" />
      <path d="M9 18 11 8l2 4 2-3 2 9" />
      <path d="M11 8c0-2 1-3 2.5-3.5" />
    </IconBase>
  )
);

IslandIcon.displayName = "IslandIcon";

export default IslandIcon;
