import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ItalicIcon ("italic")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ItalicIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="10" y1="4" x2="18" y2="4" />
      <line x1="6" y1="20" x2="14" y2="20" />
      <line x1="14" y1="4" x2="10" y2="20" />
    </IconBase>
  )
);

ItalicIcon.displayName = "ItalicIcon";

export default ItalicIcon;
