import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * JoystickIcon ("joystick")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const JoystickIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="7" r="3.5" />
      <line x1="12" y1="10.5" x2="12" y2="16" />
      <path d="M6 16h12l-1.5 4h-9Z" />
    </IconBase>
  )
);

JoystickIcon.displayName = "JoystickIcon";

export default JoystickIcon;
