import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * KanbanIcon ("kanban")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const KanbanIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="4" width="18" height="16" rx="2" />
      <line x1="9.5" y1="4" x2="9.5" y2="20" />
      <line x1="15" y1="4" x2="15" y2="20" />
      <line x1="5.5" y1="8" x2="7.5" y2="8" />
      <line x1="5.5" y1="11" x2="7.5" y2="11" />
      <line x1="12" y1="8" x2="13" y2="8" />
    </IconBase>
  )
);

KanbanIcon.displayName = "KanbanIcon";

export default KanbanIcon;
