import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * KettleIcon ("kettle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const KettleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 12a7 6 0 0 1 14 0v3a5 4 0 0 1-5 4h-4a5 4 0 0 1-5-4Z" />
      <path d="M5 12H2.5" />
      <path d="M19 10h2.5" />
      <line x1="12" y1="4.5" x2="12" y2="2" />
      <circle cx="12" cy="2" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

KettleIcon.displayName = "KettleIcon";

export default KettleIcon;
