import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * KeyIcon ("key")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const KeyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="7" cy="15" r="4" />
      <line x1="10" y1="12" x2="20" y2="2" />
      <line x1="17" y1="5" x2="19" y2="7" />
      <line x1="14.5" y1="7.5" x2="16.5" y2="9.5" />
    </IconBase>
  )
);

KeyIcon.displayName = "KeyIcon";

export default KeyIcon;
