import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * KeyboardIcon ("keyboard")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const KeyboardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="5.5" width="19" height="13" rx="1.5" />
      <line x1="6" y1="9.5" x2="8" y2="9.5" />
      <line x1="11" y1="9.5" x2="13" y2="9.5" />
      <line x1="16" y1="9.5" x2="18" y2="9.5" />
      <line x1="6" y1="13.5" x2="18" y2="13.5" />
    </IconBase>
  )
);

KeyboardIcon.displayName = "KeyboardIcon";

export default KeyboardIcon;
