import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * KnifeIcon ("knife")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const KnifeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="3.5" y1="20.5" x2="13" y2="11" />
      <path d="M13 11 18.5 5.5a2.2 2.2 0 0 1 3 3.2L16 14" />
    </IconBase>
  )
);

KnifeIcon.displayName = "KnifeIcon";

export default KnifeIcon;
