import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LampIcon ("lamp")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LampIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3h12l-3 8H9Z" />
      <line x1="12" y1="11" x2="12" y2="18" />
      <line x1="8" y1="21" x2="16" y2="21" />
      <line x1="9" y1="18" x2="15" y2="18" />
    </IconBase>
  )
);

LampIcon.displayName = "LampIcon";

export default LampIcon;
