import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LaptopIcon ("laptop")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LaptopIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4" y="4.5" width="16" height="11" rx="1.5" />
      <line x1="2" y1="19.5" x2="22" y2="19.5" />
    </IconBase>
  )
);

LaptopIcon.displayName = "LaptopIcon";

export default LaptopIcon;
