import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LaughIcon ("laugh")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LaughIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <circle cx="9" cy="10" r="1" fill="currentColor" stroke="none" />
      <circle cx="15" cy="10" r="1" fill="currentColor" stroke="none" />
      <path d="M7.5 14a4.5 4 0 0 0 9 0" />
      <line x1="8.5" y1="15.5" x2="15.5" y2="15.5" />
    </IconBase>
  )
);

LaughIcon.displayName = "LaughIcon";

export default LaughIcon;
