import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LayersIcon ("layers")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LayersIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polygon points="12 3.5 21 8.5 12 13.5 3 8.5" />
      <polyline points="3 13.5 12 18.5 21 13.5" />
    </IconBase>
  )
);

LayersIcon.displayName = "LayersIcon";

export default LayersIcon;
