import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LeafIcon ("leaf")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LeafIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 20c0-9 5-15 15-15 1 8-4 15-15 15Z" />
      <path d="M5 19c3-4 6-7 12-11" />
    </IconBase>
  )
);

LeafIcon.displayName = "LeafIcon";

export default LeafIcon;
