import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LighthouseIcon ("lighthouse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LighthouseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M10 22 8 9h8l-2 13Z" />
      <path d="M9 9 10 3h4l1 6" />
      <line x1="7" y1="14" x2="17" y2="14" />
      <line x1="4" y1="6" x2="7" y2="7.5" />
      <line x1="20" y1="6" x2="17" y2="7.5" />
    </IconBase>
  )
);

LighthouseIcon.displayName = "LighthouseIcon";

export default LighthouseIcon;
