import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LightbulbIcon ("lightbulb")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LightbulbIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 18h6" />
      <path d="M10 21h4" />
      <path d="M12 3a6.5 6.5 0 0 0-4 11.6c.7.6 1 1.2 1 2.4h6c0-1.2.3-1.8 1-2.4A6.5 6.5 0 0 0 12 3Z" />
    </IconBase>
  )
);

LightbulbIcon.displayName = "LightbulbIcon";

export default LightbulbIcon;
