import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LinkIcon ("link")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LinkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9.5 14.5 14.5 9.5" />
      <path d="M11 7 13 5a3.5 3.5 0 0 1 5 5l-2 2" />
      <path d="M13 17l-2 2a3.5 3.5 0 0 1-5-5l2-2" />
    </IconBase>
  )
);

LinkIcon.displayName = "LinkIcon";

export default LinkIcon;
