import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ListOrderedIcon ("list-ordered")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ListOrderedIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="9" y1="6" x2="20" y2="6" />
      <line x1="9" y1="12" x2="20" y2="12" />
      <line x1="9" y1="18" x2="20" y2="18" />
      <line x1="4.5" y1="4.5" x2="4.5" y2="7.5" />
      <line x1="4.5" y1="10.5" x2="4.5" y2="13.5" />
      <line x1="4.5" y1="16.5" x2="4.5" y2="19.5" />
    </IconBase>
  )
);

ListOrderedIcon.displayName = "ListOrderedIcon";

export default ListOrderedIcon;
