import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LocationArrowIcon ("location-arrow")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LocationArrowIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 4 20 11 12.5 13.5 10 21Z" />
    </IconBase>
  )
);

LocationArrowIcon.displayName = "LocationArrowIcon";

export default LocationArrowIcon;
