import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LogInIcon ("log-in")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LogInIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M15 4h4a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-4" />
      <line x1="3" y1="12" x2="14.5" y2="12" />
      <polyline points="10 7.5 14.5 12 10 16.5" />
    </IconBase>
  )
);

LogInIcon.displayName = "LogInIcon";

export default LogInIcon;
