import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LogOutIcon ("log-out")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LogOutIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h4" />
      <line x1="21" y1="12" x2="9.5" y2="12" />
      <polyline points="17 7.5 21 12 17 16.5" />
    </IconBase>
  )
);

LogOutIcon.displayName = "LogOutIcon";

export default LogOutIcon;
