import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LuggageIcon ("luggage")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LuggageIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4.5" y="7.5" width="15" height="13" rx="2" />
      <path d="M9 7.5V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2.5" />
      <line x1="12" y1="11" x2="12" y2="16.5" />
    </IconBase>
  )
);

LuggageIcon.displayName = "LuggageIcon";

export default LuggageIcon;
