import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * LungsIcon ("lungs")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const LungsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3v9" />
      <path d="M12 12c-1-3-3-4-5-4-2.5 0-3.5 2-3 5 .5 3 2 6.5 4.5 6.5 2 0 3-1.5 3.5-3.5" />
      <path d="M12 12c1-3 3-4 5-4 2.5 0 3.5 2 3 5-.5 3-2 6.5-4.5 6.5-2 0-3-1.5-3.5-3.5" />
    </IconBase>
  )
);

LungsIcon.displayName = "LungsIcon";

export default LungsIcon;
