import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MagicWandIcon ("magic-wand")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MagicWandIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4.5" y1="19.5" x2="15" y2="9" />
      <line x1="17" y1="3" x2="17" y2="6" />
      <line x1="21" y1="7" x2="18" y2="7" />
      <line x1="19.5" y1="4.5" x2="17.5" y2="6.5" />
    </IconBase>
  )
);

MagicWandIcon.displayName = "MagicWandIcon";

export default MagicWandIcon;
