import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MagnetIcon ("magnet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MagnetIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3.5 3 6.5v5a9 9 0 0 0 18 0v-5l-3-3" />
      <line x1="3" y1="10" x2="8" y2="10" />
      <line x1="16" y1="10" x2="21" y2="10" />
    </IconBase>
  )
);

MagnetIcon.displayName = "MagnetIcon";

export default MagnetIcon;
