import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MailIcon ("mail")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MailIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="5" width="18" height="14" rx="2" />
      <polyline points="3.5 6 12 13 20.5 6" />
    </IconBase>
  )
);

MailIcon.displayName = "MailIcon";

export default MailIcon;
