import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MapPinIcon ("map-pin")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MapPinIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 21.5S19 14.6 19 9.5a7 7 0 0 0-14 0c0 5.1 7 12 7 12Z" />
      <circle cx="12" cy="9.5" r="2.3" />
    </IconBase>
  )
);

MapPinIcon.displayName = "MapPinIcon";

export default MapPinIcon;
