import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MaskIcon ("mask")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MaskIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 6c3-2 15-2 18 0-1 6-4 10-9 10S4 12 3 6Z" />
      <circle cx="8.5" cy="8.5" r="1" fill="currentColor" stroke="none" />
      <circle cx="15.5" cy="8.5" r="1" fill="currentColor" stroke="none" />
      <path d="M9 13q3 2 6 0" />
    </IconBase>
  )
);

MaskIcon.displayName = "MaskIcon";

export default MaskIcon;
