import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MaximizeIcon ("maximize")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MaximizeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5H4v4" />
      <path d="M16 3.5h4v4" />
      <path d="M8 20.5H4v-4" />
      <path d="M16 20.5h4v-4" />
    </IconBase>
  )
);

MaximizeIcon.displayName = "MaximizeIcon";

export default MaximizeIcon;
