import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MedalIcon ("medal")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MedalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="15" r="5.5" />
      <path d="M9.5 10 7 3.5h3l2 5" />
      <path d="M14.5 10 17 3.5h-3l-2 5" />
      <path d="M10.5 17 12 13l1.5 4-1.5-1-1.5 1Z" />
    </IconBase>
  )
);

MedalIcon.displayName = "MedalIcon";

export default MedalIcon;
