import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MeditationIcon ("meditation")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MeditationIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="5.5" r="1.8" />
      <path d="M12 7.5v4" />
      <path d="M12 8.5 7 12a3 3 0 0 0 0 4" />
      <path d="M12 8.5 17 12a3 3 0 0 1 0 4" />
      <path d="M7 16h10" />
      <path d="M9 16c0 2-1.5 3-3 3.5" />
      <path d="M15 16c0 2 1.5 3 3 3.5" />
    </IconBase>
  )
);

MeditationIcon.displayName = "MeditationIcon";

export default MeditationIcon;
