import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MegaphoneIcon ("megaphone")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MegaphoneIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 10.5v3a1.5 1.5 0 0 0 1.5 1.5H6l1.5 4.5h2L8 15h2.5L18 18.5V5.5L10.5 9H4.5A1.5 1.5 0 0 0 3 10.5Z" />
      <path d="M20 8.5a4 4 0 0 1 0 7" />
    </IconBase>
  )
);

MegaphoneIcon.displayName = "MegaphoneIcon";

export default MegaphoneIcon;
