import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MemoryCardIcon ("memory-card")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MemoryCardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3.5h9l3 3V20a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1Z" />
      <line x1="8" y1="3.5" x2="8" y2="8" />
      <line x1="11" y1="3.5" x2="11" y2="8" />
      <line x1="14" y1="6.5" x2="14" y2="8" />
      <line x1="7" y1="8" x2="17" y2="8" />
    </IconBase>
  )
);

MemoryCardIcon.displayName = "MemoryCardIcon";

export default MemoryCardIcon;
