import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MessageCircleIcon ("message-circle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MessageCircleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12a8 8 0 1 1 3.5 6.6L4 20l1.4-3.8A7.9 7.9 0 0 1 4 12Z" />
    </IconBase>
  )
);

MessageCircleIcon.displayName = "MessageCircleIcon";

export default MessageCircleIcon;
