import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MeteorIcon ("meteor")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MeteorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="15" cy="9" r="4" />
      <line x1="11" y1="13" x2="4" y2="20" />
      <line x1="9" y1="10.5" x2="5.5" y2="14" />
    </IconBase>
  )
);

MeteorIcon.displayName = "MeteorIcon";

export default MeteorIcon;
