import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MicOffIcon ("mic-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MicOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="9" y="2.5" width="6" height="11" rx="3" />
      <path d="M5.5 11v1a6.5 6.5 0 0 0 9.5 5.8" />
      <path d="M18.5 12v-1" />
      <line x1="12" y1="18" x2="12" y2="21.5" />
      <line x1="8.5" y1="21.5" x2="15.5" y2="21.5" />
      <line x1="3.5" y1="2.5" x2="20.5" y2="21.5" />
    </IconBase>
  )
);

MicOffIcon.displayName = "MicOffIcon";

export default MicOffIcon;
