import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MicrowaveIcon ("microwave")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MicrowaveIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="5.5" width="19" height="13" rx="1.5" />
      <rect x="5" y="8" width="9" height="7.5" rx="1" />
      <circle cx="18" cy="9.5" r="0.8" fill="currentColor" stroke="none" />
      <line x1="16.5" y1="12.5" x2="19.5" y2="12.5" />
    </IconBase>
  )
);

MicrowaveIcon.displayName = "MicrowaveIcon";

export default MicrowaveIcon;
