import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MicroscopeIcon ("microscope")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MicroscopeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 20.5h7" />
      <path d="M11 20.5V17" />
      <path d="M7.5 17h7a2 2 0 0 0 2-2v-1a2 2 0 0 0-2-2h-1" />
      <circle cx="10" cy="9.5" r="3.5" />
      <path d="M8 6.5 6.5 3.5" />
      <line x1="4.5" y1="4.5" x2="8.5" y2="2.5" />
      <line x1="4" y1="20.5" x2="14" y2="20.5" />
    </IconBase>
  )
);

MicroscopeIcon.displayName = "MicroscopeIcon";

export default MicroscopeIcon;
