import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MilestoneIcon ("milestone")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MilestoneIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 21V3" />
      <path d="M6 5h11l-3 3.5L17 12H6" />
    </IconBase>
  )
);

MilestoneIcon.displayName = "MilestoneIcon";

export default MilestoneIcon;
