import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MilkIcon ("milk")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MilkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 2.5h6v3.5l1.5 2.5V20a1.5 1.5 0 0 1-1.5 1.5H9A1.5 1.5 0 0 1 7.5 20V8.5L9 6Z" />
      <line x1="7.5" y1="12" x2="16.5" y2="12" />
    </IconBase>
  )
);

MilkIcon.displayName = "MilkIcon";

export default MilkIcon;
