import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MinusSquareIcon ("minus-square")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MinusSquareIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="2" />
      <line x1="8" y1="12" x2="16" y2="12" />
    </IconBase>
  )
);

MinusSquareIcon.displayName = "MinusSquareIcon";

export default MinusSquareIcon;
