import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MoonStarIcon ("moon-star")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MoonStarIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M14.5 3.5A8 8 0 1 0 18.5 17a8.5 8.5 0 0 1-4-13.5Z" />
      <path d="M19 3 19.8 5 22 5.8 19.8 6.6 19 8.5 18.2 6.6 16 5.8 18.2 5Z" />
    </IconBase>
  )
);

MoonStarIcon.displayName = "MoonStarIcon";

export default MoonStarIcon;
