import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MotorcycleIcon ("motorcycle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MotorcycleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="5.5" cy="17.5" r="3" />
      <circle cx="18" cy="17.5" r="3" />
      <path d="M5.5 17.5 9 10h5l4 7.5" />
      <path d="M9 10 7 6.5h3" />
      <line x1="14" y1="10" x2="14" y2="7" />
    </IconBase>
  )
);

MotorcycleIcon.displayName = "MotorcycleIcon";

export default MotorcycleIcon;
