import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MountainIcon ("mountain")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MountainIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 20 9 8l4 6 2-3 6 9Z" />
    </IconBase>
  )
);

MountainIcon.displayName = "MountainIcon";

export default MountainIcon;
