import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MouseIcon ("mouse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MouseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="7" y="2.5" width="10" height="19" rx="5" />
      <line x1="12" y1="2.5" x2="12" y2="9" />
    </IconBase>
  )
);

MouseIcon.displayName = "MouseIcon";

export default MouseIcon;
