import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MoveDiagonalIcon ("move-diagonal")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MoveDiagonalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="7 17 17 7" />
      <polyline points="10 7 17 7 17 14" />
      <polyline points="14 17 7 17 7 10" />
    </IconBase>
  )
);

MoveDiagonalIcon.displayName = "MoveDiagonalIcon";

export default MoveDiagonalIcon;
