import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * MuscleIcon ("muscle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const MuscleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 14c0-4 2-8 6-9 1 2-1 3-1 5 3-1 6 0 7 3 1 2.5 0 5-2 6.5-2.5 2-6 2-8.5.5" />
      <path d="M4 14c0 3 2 5 5 5" />
    </IconBase>
  )
);

MuscleIcon.displayName = "MuscleIcon";

export default MuscleIcon;
