import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * NavigationIcon ("navigation")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const NavigationIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polygon points="12 2.5 19 20.5 12 16.5 5 20.5" />
    </IconBase>
  )
);

NavigationIcon.displayName = "NavigationIcon";

export default NavigationIcon;
