import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * NecktieIcon ("necktie")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const NecktieIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9.5 3.5h5l-1 4-1.5 1-1.5-1Z" />
      <path d="M10.5 8.5 8 18l4 3 4-3-2.5-9.5Z" />
    </IconBase>
  )
);

NecktieIcon.displayName = "NecktieIcon";

export default NecktieIcon;
