import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * NotebookIcon ("notebook")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const NotebookIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4.5" y="3" width="15" height="18" rx="1.5" />
      <line x1="8.5" y1="3" x2="8.5" y2="21" />
      <line x1="3" y1="7" x2="4.5" y2="7" />
      <line x1="3" y1="11" x2="4.5" y2="11" />
      <line x1="3" y1="15" x2="4.5" y2="15" />
    </IconBase>
  )
);

NotebookIcon.displayName = "NotebookIcon";

export default NotebookIcon;
