import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * OctagonIcon ("octagon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const OctagonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3h8l5 5v8l-5 5H8l-5-5V8Z" />
    </IconBase>
  )
);

OctagonIcon.displayName = "OctagonIcon";

export default OctagonIcon;
