import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * OfficeChairIcon ("office-chair")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const OfficeChairIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="7" y="3.5" width="10" height="7" rx="1.5" />
      <path d="M7 10.5 5 15h14l-2-4.5" />
      <line x1="12" y1="15" x2="12" y2="19" />
      <line x1="8" y1="21.5" x2="16" y2="21.5" />
      <line x1="12" y1="19" x2="12" y2="21.5" />
    </IconBase>
  )
);

OfficeChairIcon.displayName = "OfficeChairIcon";

export default OfficeChairIcon;
