import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * OrbitIcon ("orbit")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const OrbitIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="19" cy="5" r="1.6" />
      <path d="M19 5a9.5 4 -20 1 1-14 8" />
    </IconBase>
  )
);

OrbitIcon.displayName = "OrbitIcon";

export default OrbitIcon;
