import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * OrnamentIcon ("ornament")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const OrnamentIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="14" r="7" />
      <path d="M10 4h4l-1 3h-2Z" />
      <line x1="12" y1="7" x2="12" y2="9" />
    </IconBase>
  )
);

OrnamentIcon.displayName = "OrnamentIcon";

export default OrnamentIcon;
