import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * OvenIcon ("oven")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const OvenIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="3.5" width="18" height="17" rx="1.5" />
      <circle cx="12" cy="14" r="4" />
      <line x1="6" y1="7" x2="9" y2="7" />
      <line x1="11" y1="7" x2="14" y2="7" />
      <line x1="16" y1="7" x2="18" y2="7" />
    </IconBase>
  )
);

OvenIcon.displayName = "OvenIcon";

export default OvenIcon;
