import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PackageCheckIcon ("package-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PackageCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 7 12 3l8.5 4v10L12 21l-8.5-4Z" />
      <line x1="3.5" y1="7" x2="12" y2="11" />
      <line x1="20.5" y1="7" x2="12" y2="11" />
      <line x1="12" y1="11" x2="12" y2="21" />
      <polyline points="15.5 13.5 17 15 20 11.5" />
    </IconBase>
  )
);

PackageCheckIcon.displayName = "PackageCheckIcon";

export default PackageCheckIcon;
