import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PackageIcon ("package")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PackageIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5 21 7.5v9L12 21.5 3 16.5v-9Z" />
      <path d="M3 7.5 12 12.5 21 7.5" />
      <line x1="12" y1="12.5" x2="12" y2="21.5" />
    </IconBase>
  )
);

PackageIcon.displayName = "PackageIcon";

export default PackageIcon;
