import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PaintRollerIcon ("paint-roller")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PaintRollerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="4" y="4" width="14" height="6" rx="1.5" />
      <line x1="8" y1="10" x2="8" y2="15" />
      <rect x="6" y="15" width="4" height="5" rx="1" />
    </IconBase>
  )
);

PaintRollerIcon.displayName = "PaintRollerIcon";

export default PaintRollerIcon;
