import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PanelLeftIcon ("panel-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PanelLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="4" width="18" height="16" rx="2" />
      <rect x="3" y="4" width="6.5" height="16" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

PanelLeftIcon.displayName = "PanelLeftIcon";

export default PanelLeftIcon;
