import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PanelRightIcon ("panel-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PanelRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="4" width="18" height="16" rx="2" />
      <rect x="14.5" y="4" width="6.5" height="16" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

PanelRightIcon.displayName = "PanelRightIcon";

export default PanelRightIcon;
