import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PaperclipIcon ("paperclip")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PaperclipIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M18 10.5 10.5 18a3.5 3.5 0 0 1-5-5L14.3 4.3a2.5 2.5 0 0 1 3.5 3.5L9.5 16a1 1 0 0 1-1.5-1.5l7-7" />
    </IconBase>
  )
);

PaperclipIcon.displayName = "PaperclipIcon";

export default PaperclipIcon;
