import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ParallelogramIcon ("parallelogram")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ParallelogramIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 5h13l-4 14H4Z" />
    </IconBase>
  )
);

ParallelogramIcon.displayName = "ParallelogramIcon";

export default ParallelogramIcon;
