import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ParkingIcon ("parking")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ParkingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="2" />
      <path d="M9 16.5v-9h3.5a3 3 0 0 1 0 6H9" />
    </IconBase>
  )
);

ParkingIcon.displayName = "ParkingIcon";

export default ParkingIcon;
