import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PartyPopperIcon ("party-popper")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PartyPopperIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 20 14 10" />
      <path d="M14 4v3" />
      <path d="M20 10h-3" />
      <path d="M18 5.5 16 7.5" />
      <circle cx="9" cy="15" r="0.8" fill="currentColor" stroke="none" />
      <circle cx="6" cy="12" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="12" cy="18" r="0.6" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

PartyPopperIcon.displayName = "PartyPopperIcon";

export default PartyPopperIcon;
