import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PassportIcon ("passport")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PassportIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="5.5" y="3" width="13" height="18" rx="1.5" />
      <circle cx="12" cy="9.5" r="2.3" />
      <line x1="9" y1="14.5" x2="15" y2="14.5" />
      <line x1="9" y1="17" x2="15" y2="17" />
    </IconBase>
  )
);

PassportIcon.displayName = "PassportIcon";

export default PassportIcon;
