import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PencilIcon ("pencil")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PencilIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 20 5 15.5 15.5 5a2 2 0 0 1 2.8 0l.7.7a2 2 0 0 1 0 2.8L8.5 19Z" />
      <line x1="13.5" y1="7" x2="17" y2="10.5" />
    </IconBase>
  )
);

PencilIcon.displayName = "PencilIcon";

export default PencilIcon;
