import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PentagonIcon ("pentagon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PentagonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 21 9.7 17.5 20.5H6.5L3 9.7Z" />
    </IconBase>
  )
);

PentagonIcon.displayName = "PentagonIcon";

export default PentagonIcon;
