import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PenToolIcon ("pen-tool")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PenToolIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 19 5 12l4.5-4.5L17 15Z" />
      <circle cx="7" cy="17" r="2" />
      <line x1="15" y1="4" x2="20" y2="9" />
    </IconBase>
  )
);

PenToolIcon.displayName = "PenToolIcon";

export default PenToolIcon;
