import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PhoneCallIcon ("phone-call")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PhoneCallIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.6 3.5 9.4 8a1 1 0 0 1-.3 1.3l-2 1.4a13 13 0 0 0 6.2 6.2l1.4-2a1 1 0 0 1 1.3-.3l4.5 2.8a1 1 0 0 1 .4 1.3l-1 2.1a2 2 0 0 1-2 1.1A17.5 17.5 0 0 1 3.2 6.4a2 2 0 0 1 1.1-2l2.1-1a1 1 0 0 1 .2.1Z" />
      <path d="M15 6a3 3 0 0 1 3 3" />
      <path d="M15 2.5a6.5 6.5 0 0 1 6.5 6.5" />
    </IconBase>
  )
);

PhoneCallIcon.displayName = "PhoneCallIcon";

export default PhoneCallIcon;
