import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PhoneOffIcon ("phone-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PhoneOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M10.5 5 9.4 8a1 1 0 0 1-.3 1.3l-2 1.4a13 13 0 0 0 6.2 6.2l1.4-2a1 1 0 0 1 1.3-.3l4.5 2.8a1 1 0 0 1 .4 1.3l-1 2.1a2 2 0 0 1-2 1.1 17.4 17.4 0 0 1-7.8-3.3" />
      <path d="M3.5 6.4a2 2 0 0 1 1.1-2L6.6 3.5" />
      <line x1="3" y1="3" x2="21" y2="21" />
    </IconBase>
  )
);

PhoneOffIcon.displayName = "PhoneOffIcon";

export default PhoneOffIcon;
