import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PiIcon ("pi")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PiIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="6" x2="20" y2="6" />
      <path d="M8 6v11a3 3 0 0 0 3 3" />
      <path d="M16 6v11a3 3 0 0 1-3 3" />
    </IconBase>
  )
);

PiIcon.displayName = "PiIcon";

export default PiIcon;
