import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PiggyBankIcon ("piggy-bank")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PiggyBankIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 13a6 5.5 0 0 1 6-5.5h5a4 4 0 0 1 4 4v1l2 1.5-2 1v1.5a1.5 1.5 0 0 1-1.5 1.5H16v2h-2.5v-2H8.5a4.5 4.5 0 0 1-4.5-4.5Z" />
      <circle cx="15" cy="12" r="0.9" fill="currentColor" stroke="none" />
      <line x1="8" y1="7.8" x2="8" y2="5.5" />
    </IconBase>
  )
);

PiggyBankIcon.displayName = "PiggyBankIcon";

export default PiggyBankIcon;
