import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PilcrowIcon ("pilcrow")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PilcrowIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9.5 3.5h7v9a3.5 3.5 0 0 1-7 0Z" />
      <line x1="13" y1="3.5" x2="13" y2="20.5" />
      <line x1="16.5" y1="3.5" x2="16.5" y2="20.5" />
    </IconBase>
  )
);

PilcrowIcon.displayName = "PilcrowIcon";

export default PilcrowIcon;
