import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PillIcon ("pill")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PillIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7.5 16.5 16.5 7.5a4 4 0 1 1 5.7 5.7L13.2 22.2a4 4 0 0 1-5.7-5.7Z" />
      <line x1="10.5" y1="13.5" x2="14.8" y2="9.2" />
    </IconBase>
  )
);

PillIcon.displayName = "PillIcon";

export default PillIcon;
