import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PinIcon ("pin")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PinIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5a5.5 5.5 0 0 0-5.5 5.5c0 3 2 4.5 3.5 6l2 6 2-6c1.5-1.5 3.5-3 3.5-6A5.5 5.5 0 0 0 12 2.5Z" />
      <circle cx="12" cy="8" r="2" />
    </IconBase>
  )
);

PinIcon.displayName = "PinIcon";

export default PinIcon;
