import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PinOffIcon ("pin-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PinOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5a5.5 5.5 0 0 0-5.5 5.5c0 1.5.5 2.7 1.3 3.8" />
      <path d="M9.5 14.7c.7.7 1.3 1.4 1.7 2.3l.8 3 1.5-4.5c1.5-1.5 3.5-3 3.5-6a5.5 5.5 0 0 0-2.2-4.4" />
      <line x1="3" y1="3" x2="21" y2="21" />
    </IconBase>
  )
);

PinOffIcon.displayName = "PinOffIcon";

export default PinOffIcon;
