import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PizzaIcon ("pizza")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PizzaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 3 20h18Z" />
      <circle cx="11" cy="12" r="1" fill="currentColor" stroke="none" />
      <circle cx="14" cy="16" r="1" fill="currentColor" stroke="none" />
      <circle cx="9" cy="16.5" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

PizzaIcon.displayName = "PizzaIcon";

export default PizzaIcon;
