import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PlaneIcon ("plane")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PlaneIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5v8.5" />
      <path d="M12 11l8 5v1.8l-8-2.2" />
      <path d="M12 11 4 16v1.8l8-2.2" />
      <path d="M9.8 16.5 8.2 19h7.6l-1.6-2.5" />
    </IconBase>
  )
);

PlaneIcon.displayName = "PlaneIcon";

export default PlaneIcon;
