import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PlanetIcon ("planet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PlanetIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="5.5" />
      <path d="M2.5 14a20 6 -15 1 0 19-8" />
    </IconBase>
  )
);

PlanetIcon.displayName = "PlanetIcon";

export default PlanetIcon;
