import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PlaneLandingIcon ("plane-landing")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PlaneLandingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5v6" />
      <path d="M12 8.5l7 4.5v1.8l-7-2.2" />
      <path d="M12 8.5 5 13v1.8l7-2.2" />
      <path d="M9.8 16 8.2 18h7.6l-1.6-2" />
      <line x1="3" y1="21" x2="21" y2="21" />
      <line x1="16" y1="3" x2="19" y2="6" />
      <polyline points="19 3.5 19 6 16.5 6" />
    </IconBase>
  )
);

PlaneLandingIcon.displayName = "PlaneLandingIcon";

export default PlaneLandingIcon;
