import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PlaneTakeoffIcon ("plane-takeoff")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PlaneTakeoffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5v6" />
      <path d="M12 8.5l7 4.5v1.8l-7-2.2" />
      <path d="M12 8.5 5 13v1.8l7-2.2" />
      <path d="M9.8 16 8.2 18h7.6l-1.6-2" />
      <line x1="3" y1="21" x2="21" y2="21" />
      <line x1="16" y1="6" x2="19" y2="3" />
      <polyline points="16.5 3 19 3 19 5.5" />
    </IconBase>
  )
);

PlaneTakeoffIcon.displayName = "PlaneTakeoffIcon";

export default PlaneTakeoffIcon;
