import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PlugIcon ("plug")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PlugIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 2.5v6" />
      <path d="M15 2.5v6" />
      <path d="M6.5 8.5h11v3a5.5 5.5 0 0 1-11 0Z" />
      <line x1="12" y1="17" x2="12" y2="21.5" />
    </IconBase>
  )
);

PlugIcon.displayName = "PlugIcon";

export default PlugIcon;
