import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PoundSignIcon ("pound-sign")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PoundSignIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 21V11a4 4 0 0 1 8-1.5" />
      <line x1="5" y1="21" x2="15" y2="21" />
      <line x1="5" y1="13.5" x2="12.5" y2="13.5" />
    </IconBase>
  )
);

PoundSignIcon.displayName = "PoundSignIcon";

export default PoundSignIcon;
