import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PowerIcon ("power")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PowerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="3" x2="12" y2="11" />
      <path d="M7 6a7.5 7.5 0 1 0 10 0" />
    </IconBase>
  )
);

PowerIcon.displayName = "PowerIcon";

export default PowerIcon;
