import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PresentationIcon ("presentation")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PresentationIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="3.5" width="19" height="12" rx="1.5" />
      <line x1="12" y1="15.5" x2="12" y2="20.5" />
      <line x1="7" y1="20.5" x2="17" y2="20.5" />
      <polyline points="6.5 12 10 8 13 10.5 17.5 6" />
    </IconBase>
  )
);

PresentationIcon.displayName = "PresentationIcon";

export default PresentationIcon;
