import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PrinterIcon ("printer")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PrinterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 8.5V3.5h12v5" />
      <rect x="2.5" y="8.5" width="19" height="9" rx="1.5" />
      <path d="M6 14h12v7H6Z" />
    </IconBase>
  )
);

PrinterIcon.displayName = "PrinterIcon";

export default PrinterIcon;
