import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ProjectorIcon ("projector")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ProjectorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="7" width="14" height="9" rx="2" />
      <circle cx="7" cy="11.5" r="2.3" />
      <circle cx="14" cy="9.5" r="1" fill="currentColor" stroke="none" />
      <path d="M16.5 11.5 21.5 8.5v6Z" />
    </IconBase>
  )
);

ProjectorIcon.displayName = "ProjectorIcon";

export default ProjectorIcon;
