import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ProtractorIcon ("protractor")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ProtractorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12a8 8 0 0 1 16 0Z" />
      <line x1="4" y1="12" x2="20" y2="12" />
      <line x1="12" y1="12" x2="12" y2="5" />
      <line x1="12" y1="12" x2="17" y2="7.5" />
    </IconBase>
  )
);

ProtractorIcon.displayName = "ProtractorIcon";

export default ProtractorIcon;
