import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PumpkinIcon ("pumpkin")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PumpkinIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4.5 13.5a7.5 6 0 0 1 15 0 7.5 6 0 0 1-15 0Z" />
      <line x1="8" y1="8.5" x2="8" y2="18.5" />
      <line x1="12" y1="7.7" x2="12" y2="19.3" />
      <line x1="16" y1="8.5" x2="16" y2="18.5" />
      <path d="M12 7.7V4.5" />
      <path d="M12 4.5c0-1 1-1.5 2-1.5" />
    </IconBase>
  )
);

PumpkinIcon.displayName = "PumpkinIcon";

export default PumpkinIcon;
