import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * PushPinIcon ("push-pin")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const PushPinIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="17" x2="12" y2="22" />
      <path d="M8 3.5h8l-1 6 3 3H6l3-3Z" />
    </IconBase>
  )
);

PushPinIcon.displayName = "PushPinIcon";

export default PushPinIcon;
