import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * QrcodeIcon ("qrcode")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const QrcodeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="3" width="7" height="7" rx="1" />
      <rect x="14" y="3" width="7" height="7" rx="1" />
      <rect x="3" y="14" width="7" height="7" rx="1" />
      <rect x="14.5" y="14.5" width="2.5" height="2.5" fill="currentColor" stroke="none" />
      <rect x="18" y="14.5" width="2.5" height="2.5" fill="currentColor" stroke="none" />
      <rect x="14.5" y="18" width="2.5" height="2.5" fill="currentColor" stroke="none" />
      <rect x="18" y="18" width="2.5" height="2.5" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

QrcodeIcon.displayName = "QrcodeIcon";

export default QrcodeIcon;
