import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * QuestionMarkIcon ("question-mark")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const QuestionMarkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 9a3 3 0 1 1 4.5 2.6c-1 .6-1.5 1.1-1.5 2.4" />
      <circle cx="12" cy="18.5" r="1.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

QuestionMarkIcon.displayName = "QuestionMarkIcon";

export default QuestionMarkIcon;
