import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * QuoteIcon ("quote")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const QuoteIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 8.5a3 3 0 0 0-3 3V15h4v-4H5a2 2 0 0 1 2-2Z" />
      <path d="M16 8.5a3 3 0 0 0-3 3V15h4v-4h-2a2 2 0 0 1 2-2Z" />
    </IconBase>
  )
);

QuoteIcon.displayName = "QuoteIcon";

export default QuoteIcon;
