import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RabbitIcon ("rabbit")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RabbitIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 9V4a1.5 1.5 0 0 1 3 0v5" />
      <path d="M12 9V4a1.5 1.5 0 0 1 3 0v5" />
      <path d="M6 12a6 6 0 0 1 12 0v2a6 6 0 0 1-12 0Z" />
      <circle cx="10" cy="12.5" r="0.7" fill="currentColor" stroke="none" />
      <circle cx="14" cy="12.5" r="0.7" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

RabbitIcon.displayName = "RabbitIcon";

export default RabbitIcon;
