import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RadiationIcon ("radiation")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RadiationIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="2" />
      <path d="M12 12 15.5 6a7 7 0 0 1 3.5 6Z" />
      <path d="M12 12 8.5 6a7 7 0 0 0-3.5 6Z" />
      <path d="M12 12 12 19a7 7 0 0 0 6.5-4.5Z" />
      <path d="M12 12 12 19a7 7 0 0 1-6.5-4.5Z" />
    </IconBase>
  )
);

RadiationIcon.displayName = "RadiationIcon";

export default RadiationIcon;
