import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RainbowIcon ("rainbow")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RainbowIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 19.5a9 9 0 0 1 18 0" />
      <path d="M6.5 19.5a5.5 5.5 0 0 1 11 0" />
    </IconBase>
  )
);

RainbowIcon.displayName = "RainbowIcon";

export default RainbowIcon;
