import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RedoIcon ("redo")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RedoIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M15 14 20 9l-5-5" />
      <path d="M20 9H10a6 6 0 0 0 0 12h3" />
    </IconBase>
  )
);

RedoIcon.displayName = "RedoIcon";

export default RedoIcon;
