import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RepeatIcon ("repeat")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RepeatIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M17 2.5 21 6.5 17 10.5" />
      <path d="M3 11.5v-2a3 3 0 0 1 3-3h15" />
      <path d="M7 21.5 3 17.5 7 13.5" />
      <path d="M21 12.5v2a3 3 0 0 1-3 3H3" />
    </IconBase>
  )
);

RepeatIcon.displayName = "RepeatIcon";

export default RepeatIcon;
