import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ReplaceIcon ("replace")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ReplaceIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="3" width="9" height="9" rx="1.5" />
      <rect x="12" y="12" width="9" height="9" rx="1.5" />
      <path d="M12 8h4a2 2 0 0 1 2 2v2" />
      <path d="M12 16H8a2 2 0 0 1-2-2v-2" />
    </IconBase>
  )
);

ReplaceIcon.displayName = "ReplaceIcon";

export default ReplaceIcon;
