import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RibbonIcon ("ribbon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RibbonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="7" r="4.5" />
      <path d="M8.5 10.5 5.5 21l6.5-4 6.5 4-3-10.5" />
    </IconBase>
  )
);

RibbonIcon.displayName = "RibbonIcon";

export default RibbonIcon;
