import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RingIcon ("ring")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="15" r="6" />
      <path d="M9 9 12 3l3 6" />
      <circle cx="12" cy="9" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

RingIcon.displayName = "RingIcon";

export default RingIcon;
