import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RoadIcon ("road")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RoadIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 3 4 21" />
      <path d="M15 3 20 21" />
      <line x1="12" y1="4" x2="12" y2="7" />
      <line x1="12" y1="10.5" x2="12" y2="13.5" />
      <line x1="12" y1="17" x2="12" y2="20" />
    </IconBase>
  )
);

RoadIcon.displayName = "RoadIcon";

export default RoadIcon;
