import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RockIcon ("rock")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RockIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 17 6 9l4-2 5 1 4 4-1 5Z" />
    </IconBase>
  )
);

RockIcon.displayName = "RockIcon";

export default RockIcon;
