import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RocketIcon ("rocket")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RocketIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5c3 2 4.5 6 4.5 10l-4.5 4-4.5-4c0-4 1.5-8 4.5-10Z" />
      <circle cx="12" cy="10" r="1.7" />
      <path d="M9 15l-3 1 1-3" />
      <path d="M15 15l3 1-1-3" />
      <path d="M10.5 19 9 22" />
      <path d="M13.5 19 15 22" />
    </IconBase>
  )
);

RocketIcon.displayName = "RocketIcon";

export default RocketIcon;
