import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RotateCwIcon ("rotate-cw")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RotateCwIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M20 12a8 8 0 1 1-2.7-6" />
      <polyline points="20 4 20 9 15 9" />
    </IconBase>
  )
);

RotateCwIcon.displayName = "RotateCwIcon";

export default RotateCwIcon;
