import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RotateCcwIcon ("rotate-ccw")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RotateCcwIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12a8 8 0 1 0 2.7-6" />
      <polyline points="4 4 4 9 9 9" />
    </IconBase>
  )
);

RotateCcwIcon.displayName = "RotateCcwIcon";

export default RotateCcwIcon;
