import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RouterIcon ("router")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RouterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="12" width="19" height="7" rx="1.5" />
      <circle cx="7" cy="15.5" r="0.8" fill="currentColor" stroke="none" />
      <circle cx="10" cy="15.5" r="0.8" fill="currentColor" stroke="none" />
      <line x1="9" y1="12" x2="9" y2="7" />
      <line x1="15" y1="12" x2="15" y2="7" />
      <path d="M7 7a3 3 0 0 1 3-3" />
      <path d="M17 7a3 3 0 0 0-3-3" />
    </IconBase>
  )
);

RouterIcon.displayName = "RouterIcon";

export default RouterIcon;
