import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RouteIcon ("route")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RouteIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="6" r="2" />
      <circle cx="18" cy="18" r="2" />
      <line x1="7.8" y1="7.3" x2="16.2" y2="16.7" stroke-dasharray="2 2.4" />
    </IconBase>
  )
);

RouteIcon.displayName = "RouteIcon";

export default RouteIcon;
