import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RulerTriangleIcon ("ruler-triangle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RulerTriangleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 20.5 20.5 20.5 3.5 3.5Z" />
      <line x1="7" y1="20.5" x2="7" y2="18" />
      <line x1="10.5" y1="20.5" x2="10.5" y2="18" />
      <line x1="14" y1="20.5" x2="14" y2="18" />
    </IconBase>
  )
);

RulerTriangleIcon.displayName = "RulerTriangleIcon";

export default RulerTriangleIcon;
