import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RulerIcon ("ruler")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RulerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 15.5 15.5 3.5l5 5-12 12Z" />
      <line x1="7.5" y1="11.5" x2="9.5" y2="13.5" />
      <line x1="10.5" y1="8.5" x2="12.5" y2="10.5" />
      <line x1="13.5" y1="5.5" x2="15.5" y2="7.5" />
    </IconBase>
  )
);

RulerIcon.displayName = "RulerIcon";

export default RulerIcon;
