import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * RunningIcon ("running")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const RunningIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="14.5" cy="4.5" r="1.8" />
      <path d="M9 20 12 15l3 2 3-1.5" />
      <path d="M12 15 9.5 11l3-2.5 2.5 3 3.5 1" />
      <path d="M9.5 11 6 12.5" />
      <path d="M9 20 6.5 22" />
    </IconBase>
  )
);

RunningIcon.displayName = "RunningIcon";

export default RunningIcon;
