import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SaladIcon ("salad")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SaladIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 12.5a8.5 6 0 0 0 17 0Z" />
      <path d="M8 12.5c0-3 1-5.5 2.5-6.5" />
      <path d="M15 12.5c0-2.5-.5-4.5-1.5-6" />
      <path d="M11.5 12.5c0-4 1-6.5 3-8" />
    </IconBase>
  )
);

SaladIcon.displayName = "SaladIcon";

export default SaladIcon;
