import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SandwichIcon ("sandwich")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SandwichIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 10.5 12 5l8.5 5.5Z" />
      <rect x="3.5" y="10.5" width="17" height="4" rx="1" />
      <path d="M4.5 14.5 6 19h12l1.5-4.5" />
    </IconBase>
  )
);

SandwichIcon.displayName = "SandwichIcon";

export default SandwichIcon;
