import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SatelliteDishIcon ("satellite-dish")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SatelliteDishIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 15 15 4l6 6-11 11a8.5 8.5 0 0 1-6-6Z" />
      <circle cx="4" cy="20" r="1.3" />
      <line x1="15" y1="4" x2="15" y2="1.5" />
    </IconBase>
  )
);

SatelliteDishIcon.displayName = "SatelliteDishIcon";

export default SatelliteDishIcon;
