import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SatelliteIcon ("satellite")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SatelliteIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="9.5" y="9.5" width="5" height="5" rx="1" />
      <line x1="7" y1="7" x2="9.5" y2="9.5" />
      <line x1="17" y1="17" x2="14.5" y2="14.5" />
      <path d="M2.5 4.5 7 9" />
      <path d="M21.5 19.5 17 15" />
      <line x1="14.5" y1="9.5" x2="19" y2="5" />
      <line x1="4" y1="20" x2="9.5" y2="14.5" />
    </IconBase>
  )
);

SatelliteIcon.displayName = "SatelliteIcon";

export default SatelliteIcon;
