import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ScaleIcon ("scale")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ScaleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="3" x2="12" y2="21" />
      <line x1="6" y1="7" x2="18" y2="7" />
      <path d="M6 7 3 13a3 3 0 0 0 6 0Z" />
      <path d="M18 7 15 13a3 3 0 0 0 6 0Z" />
      <line x1="8" y1="21" x2="16" y2="21" />
    </IconBase>
  )
);

ScaleIcon.displayName = "ScaleIcon";

export default ScaleIcon;
