import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SchoolIcon ("school")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SchoolIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 22 8.5 12 14 2 8.5Z" />
      <path d="M6 11v6c0 1.5 2.7 3 6 3s6-1.5 6-3v-6" />
      <line x1="22" y1="8.5" x2="22" y2="16" />
    </IconBase>
  )
);

SchoolIcon.displayName = "SchoolIcon";

export default SchoolIcon;
