import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ScissorsIcon ("scissors")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ScissorsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6.5" cy="6.5" r="2.2" />
      <circle cx="6.5" cy="17.5" r="2.2" />
      <line x1="8.2" y1="8" x2="19.5" y2="19" />
      <line x1="8.2" y1="16" x2="19.5" y2="5" />
    </IconBase>
  )
);

ScissorsIcon.displayName = "ScissorsIcon";

export default ScissorsIcon;
