import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ScooterIcon ("scooter")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ScooterIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="5.5" cy="18" r="2.3" />
      <circle cx="18" cy="18" r="2.3" />
      <path d="M5.5 18 9 8h3" />
      <path d="M9 8h6.5" />
      <path d="M15.5 8v4.5h2.5l1 5.5" />
      <line x1="6" y1="4" x2="10.5" y2="4" />
      <line x1="8.5" y1="4" x2="9" y2="8" />
    </IconBase>
  )
);

ScooterIcon.displayName = "ScooterIcon";

export default ScooterIcon;
