import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ScrewdriverIcon ("screwdriver")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ScrewdriverIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="20" x2="12.5" y2="11.5" />
      <path d="M12.5 11.5 17 7a2.5 2.5 0 0 0-3.5-3.5L9 8" />
    </IconBase>
  )
);

ScrewdriverIcon.displayName = "ScrewdriverIcon";

export default ScrewdriverIcon;
