import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SeedlingIcon ("seedling")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SeedlingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 20a6 6 0 0 1 6-6" />
      <path d="M12 14c0-4 2.5-6.5 7-6.5 0 4-2.5 6.5-7 6.5Z" />
      <line x1="6" y1="20" x2="18" y2="20" />
    </IconBase>
  )
);

SeedlingIcon.displayName = "SeedlingIcon";

export default SeedlingIcon;
