import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SemicircleIcon ("semicircle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SemicircleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 16a9 9 0 0 1 18 0Z" />
    </IconBase>
  )
);

SemicircleIcon.displayName = "SemicircleIcon";

export default SemicircleIcon;
