import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SendIcon ("send")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SendIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="21" y1="3" x2="10" y2="14" />
      <polygon points="21 3 14.5 21 10 14 3 10" />
    </IconBase>
  )
);

SendIcon.displayName = "SendIcon";

export default SendIcon;
