import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShareIcon ("share")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShareIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="12" r="2.3" />
      <circle cx="18" cy="6" r="2.3" />
      <circle cx="18" cy="18" r="2.3" />
      <line x1="8" y1="10.8" x2="16" y2="7.2" />
      <line x1="8" y1="13.2" x2="16" y2="16.8" />
    </IconBase>
  )
);

ShareIcon.displayName = "ShareIcon";

export default ShareIcon;
