import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShellIcon ("shell")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShellIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 18a8 8 0 0 1 16 0Z" />
      <path d="M12 10v8" />
      <path d="M8.5 12.5 9.5 18" />
      <path d="M15.5 12.5 14.5 18" />
      <path d="M12 10c0-3 1.5-5 4-6" />
    </IconBase>
  )
);

ShellIcon.displayName = "ShellIcon";

export default ShellIcon;
