import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShieldCheckIcon ("shield-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShieldCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 20 6.5V12c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6.5Z" />
      <polyline points="8.5 12 11 14.5 15.5 9.5" />
    </IconBase>
  )
);

ShieldCheckIcon.displayName = "ShieldCheckIcon";

export default ShieldCheckIcon;
