import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShieldIcon ("shield")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShieldIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 20 6.5V12c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6.5Z" />
    </IconBase>
  )
);

ShieldIcon.displayName = "ShieldIcon";

export default ShieldIcon;
