import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShieldOffIcon ("shield-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShieldOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 20 6.5V12c0 1.8-.4 3.4-1.1 4.7" />
      <path d="M6.5 8.3V12c0 5 3.5 8 5.5 9 1-.4 1.9-1 2.7-1.7" />
      <line x1="4" y1="4" x2="20" y2="20" />
    </IconBase>
  )
);

ShieldOffIcon.displayName = "ShieldOffIcon";

export default ShieldOffIcon;
