import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShieldAlertIcon ("shield-alert")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShieldAlertIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 20 6.5V12c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6.5Z" />
      <line x1="12" y1="8" x2="12" y2="13" />
      <circle cx="12" cy="16" r="0.9" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

ShieldAlertIcon.displayName = "ShieldAlertIcon";

export default ShieldAlertIcon;
