import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShipIcon ("ship")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShipIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 14.5h16l-2 5.5H6Z" />
      <path d="M6 14.5V8h5V4.5h2V8h3v6.5" />
      <line x1="3" y1="20" x2="21" y2="20" />
    </IconBase>
  )
);

ShipIcon.displayName = "ShipIcon";

export default ShipIcon;
