import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShirtIcon ("shirt")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShirtIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 3.5 3 6.5l2 3.5 3-1.5V21h8V8.5l3 1.5 2-3.5-5-3a3 3 0 0 1-6 0Z" />
    </IconBase>
  )
);

ShirtIcon.displayName = "ShirtIcon";

export default ShirtIcon;
