import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShoeIcon ("shoe")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShoeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 18.5v-4l6-3 4 1.5 5-1 3 2.5v1a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" />
      <line x1="9" y1="11.5" x2="9" y2="15" />
    </IconBase>
  )
);

ShoeIcon.displayName = "ShoeIcon";

export default ShoeIcon;
