import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ShuffleIcon ("shuffle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ShuffleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="16 3 21 3 21 8" />
      <line x1="21" y1="3" x2="3" y2="21" />
      <polyline points="16 21 21 21 21 16" />
      <line x1="3" y1="3" x2="9" y2="9" />
      <line x1="15" y1="15" x2="21" y2="21" />
    </IconBase>
  )
);

ShuffleIcon.displayName = "ShuffleIcon";

export default ShuffleIcon;
