import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SigmaIcon ("sigma")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SigmaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M17 4H6l6 8-6 8h11" />
    </IconBase>
  )
);

SigmaIcon.displayName = "SigmaIcon";

export default SigmaIcon;
