import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SignatureIcon ("signature")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SignatureIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 18q2-6 4-2t3-4 3 3 3-5 3 4 2-1" />
      <line x1="3" y1="21" x2="21" y2="21" />
    </IconBase>
  )
);

SignatureIcon.displayName = "SignatureIcon";

export default SignatureIcon;
