import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SignpostIcon ("signpost")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SignpostIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="3" x2="12" y2="21" />
      <path d="M12 6h7l-2 2.5 2 2.5h-7" />
      <path d="M12 11h-6l2 2.5-2 2.5h6" />
    </IconBase>
  )
);

SignpostIcon.displayName = "SignpostIcon";

export default SignpostIcon;
