import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SignalIcon ("signal")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SignalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="19" x2="4" y2="15" />
      <line x1="9" y1="19" x2="9" y2="11" />
      <line x1="14" y1="19" x2="14" y2="7" />
      <line x1="19" y1="19" x2="19" y2="3" />
    </IconBase>
  )
);

SignalIcon.displayName = "SignalIcon";

export default SignalIcon;
