import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SignLanguageIcon ("sign-language")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SignLanguageIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 12V5a1.3 1.3 0 0 1 2.6 0v5" />
      <path d="M10.6 10V4a1.3 1.3 0 0 1 2.6 0v6.5" />
      <path d="M13.2 10.5V6a1.3 1.3 0 0 1 2.6 0v6" />
      <path d="M5.5 14c0-1 .5-2 2-3" />
      <path d="M5.5 14c0 4.5 2.5 7.5 7 7.5s6.5-3 6.5-6.5v-3" />
    </IconBase>
  )
);

SignLanguageIcon.displayName = "SignLanguageIcon";

export default SignLanguageIcon;
