import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SimCardIcon ("sim-card")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SimCardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3.5h7l4 4V20a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1Z" />
      <rect x="9" y="10" width="6" height="6" rx="1" />
      <line x1="9" y1="13" x2="15" y2="13" />
    </IconBase>
  )
);

SimCardIcon.displayName = "SimCardIcon";

export default SimCardIcon;
