import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SirenIcon ("siren")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SirenIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 4a5 5 0 0 1 5 5v6H7V9a5 5 0 0 1 5-5Z" />
      <line x1="12" y1="4" x2="12" y2="2" />
      <line x1="5" y1="15" x2="19" y2="15" />
      <line x1="4" y1="19.5" x2="20" y2="19.5" />
      <line x1="6" y1="15" x2="6" y2="19.5" />
      <line x1="18" y1="15" x2="18" y2="19.5" />
    </IconBase>
  )
);

SirenIcon.displayName = "SirenIcon";

export default SirenIcon;
