import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SlashIcon ("slash")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SlashIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="18" y1="4" x2="6" y2="20" />
    </IconBase>
  )
);

SlashIcon.displayName = "SlashIcon";

export default SlashIcon;
