import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SleepyIcon ("sleepy")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SleepyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <path d="M7.5 10q1.5-1 3 0" />
      <path d="M13.5 10q1.5-1 3 0" />
      <line x1="9" y1="15.5" x2="15" y2="15.5" />
      <path d="M17 5h2.5l-2 2h2.5" />
    </IconBase>
  )
);

SleepyIcon.displayName = "SleepyIcon";

export default SleepyIcon;
