import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SnowflakeIcon ("snowflake")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SnowflakeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="12" y1="2.5" x2="12" y2="21.5" />
      <line x1="4.5" y1="7" x2="19.5" y2="17" />
      <line x1="19.5" y1="7" x2="4.5" y2="17" />
    </IconBase>
  )
);

SnowflakeIcon.displayName = "SnowflakeIcon";

export default SnowflakeIcon;
