import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SnowmanIcon ("snowman")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SnowmanIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="17" r="5" />
      <circle cx="12" cy="8" r="3.5" />
      <circle cx="10.5" cy="7.5" r="0.5" fill="currentColor" stroke="none" />
      <circle cx="13.5" cy="7.5" r="0.5" fill="currentColor" stroke="none" />
      <circle cx="12" cy="16" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="12" cy="18.5" r="0.6" fill="currentColor" stroke="none" />
      <path d="M9 4.5h6l-3-2Z" />
    </IconBase>
  )
);

SnowmanIcon.displayName = "SnowmanIcon";

export default SnowmanIcon;
