import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SocksIcon ("socks")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SocksIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 2.5h6V13l4 4a3 3 0 0 1-3 4.5H9a3 3 0 0 1-3-3V2.5Z" />
      <line x1="8" y1="7.5" x2="14" y2="7.5" />
    </IconBase>
  )
);

SocksIcon.displayName = "SocksIcon";

export default SocksIcon;
