import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SofaIcon ("sofa")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SofaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v4" />
      <path d="M3 12h18v5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Z" />
      <line x1="4" y1="18" x2="4" y2="20.5" />
      <line x1="20" y1="18" x2="20" y2="20.5" />
    </IconBase>
  )
);

SofaIcon.displayName = "SofaIcon";

export default SofaIcon;
