import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SoupIcon ("soup")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SoupIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12h16v3a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5Z" />
      <path d="M4 12a2 2 0 0 1 0-4" />
      <path d="M20 12a2 2 0 0 0 0-4" />
      <path d="M9 8c0-2-1-2.5-1-4" />
      <path d="M13 8c0-2-1-2.5-1-4" />
    </IconBase>
  )
);

SoupIcon.displayName = "SoupIcon";

export default SoupIcon;
