import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SparkIcon ("spark")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SparkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2v6" />
      <path d="M12 16v6" />
      <path d="M4.5 12h6" />
      <path d="M13.5 12h6" />
    </IconBase>
  )
);

SparkIcon.displayName = "SparkIcon";

export default SparkIcon;
