import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SparklesIcon ("sparkles")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SparklesIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M11 2 12.3 8.7 19 10 12.3 11.3 11 18 9.7 11.3 3 10 9.7 8.7Z" />
      <circle cx="18.5" cy="4.5" r="1" fill="currentColor" stroke="none" />
      <circle cx="19" cy="17" r="1.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

SparklesIcon.displayName = "SparklesIcon";

export default SparklesIcon;
