import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SpeakerIcon ("speaker")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SpeakerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="5" y="2.5" width="14" height="19" rx="2" />
      <circle cx="12" cy="8" r="2.5" />
      <circle cx="12" cy="16" r="3.5" />
      <circle cx="12" cy="16" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

SpeakerIcon.displayName = "SpeakerIcon";

export default SpeakerIcon;
