import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SpoonIcon ("spoon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SpoonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M9 3.5a4 5 0 1 0 0 10 4 5 0 0 0 0-10Z" />
      <line x1="9" y1="13.5" x2="9" y2="21" />
    </IconBase>
  )
);

SpoonIcon.displayName = "SpoonIcon";

export default SpoonIcon;
