import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SproutIcon ("sprout")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SproutIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 20a5 5 0 0 1 5-5V9" />
      <path d="M12 9c0-3 2-5 6-5 0 3.5-2 5-6 5Z" />
      <path d="M12 9c0-2.5-1.7-4-5-4 0 2.8 1.7 4 5 4Z" />
      <line x1="7" y1="20" x2="17" y2="20" />
    </IconBase>
  )
);

SproutIcon.displayName = "SproutIcon";

export default SproutIcon;
