import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SquareRootIcon ("square-root")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SquareRootIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 13 6 16 10 4" />
      <line x1="10" y1="4" x2="21" y2="4" />
    </IconBase>
  )
);

SquareRootIcon.displayName = "SquareRootIcon";

export default SquareRootIcon;
