import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SquirrelIcon ("squirrel")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SquirrelIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M5 20c-1.5-4 0-9 4-11 3-1.5 6.5 0 7 3.5.3 2-1 3-2.5 2.5" />
      <circle cx="9.5" cy="9" r="0.6" fill="currentColor" stroke="none" />
      <path d="M16 12.5c3-1 5 1.5 4.5 4.5-.3 2-2 3-4 2.5" />
      <path d="M5 20a3 3 0 0 1 3-3.5" />
    </IconBase>
  )
);

SquirrelIcon.displayName = "SquirrelIcon";

export default SquirrelIcon;
