import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StampIcon ("stamp")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StampIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 14.5V11a4 4 0 0 1 8 0v3.5" />
      <rect x="4" y="14.5" width="16" height="4" rx="1" />
      <line x1="3" y1="21" x2="21" y2="21" />
    </IconBase>
  )
);

StampIcon.displayName = "StampIcon";

export default StampIcon;
