import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StaplerIcon ("stapler")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StaplerIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 16.5 20 12l1.5 4.5L4 21Z" />
      <path d="M4 21 2.5 16.5" />
      <line x1="8" y1="14.5" x2="9" y2="18.5" />
    </IconBase>
  )
);

StaplerIcon.displayName = "StaplerIcon";

export default StaplerIcon;
