import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StarHalfIcon ("star-half")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StarHalfIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 14.6 9.2 21.3 9.8 16.2 14.1 17.8 20.7 12 17.1Z" fill="currentColor" stroke="currentColor" />
      <path d="M12 3 9.4 9.2 2.7 9.8 7.8 14.1 6.2 20.7 12 17.1Z" />
    </IconBase>
  )
);

StarHalfIcon.displayName = "StarHalfIcon";

export default StarHalfIcon;
