import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StethoscopeIcon ("stethoscope")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StethoscopeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 3v6a4 4 0 0 0 8 0V3" />
      <path d="M14 12v2a5 5 0 0 1-10 0v-2" />
      <circle cx="18" cy="15" r="2.5" />
      <line x1="14" y1="12" x2="15.7" y2="13.5" />
    </IconBase>
  )
);

StethoscopeIcon.displayName = "StethoscopeIcon";

export default StethoscopeIcon;
