import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StoreIcon ("store")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StoreIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 9 4.5 4h15L21 9" />
      <path d="M3 9v11h18V9" />
      <path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0" />
      <line x1="9" y1="14" x2="9" y2="20" />
      <line x1="15" y1="14" x2="15" y2="20" />
      <line x1="9" y1="14" x2="15" y2="14" />
    </IconBase>
  )
);

StoreIcon.displayName = "StoreIcon";

export default StoreIcon;
