import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StretchingIcon ("stretching")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StretchingIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="17" cy="4.5" r="1.8" />
      <path d="M17 6.5 12 9l-5-3" />
      <path d="M12 9v6" />
      <path d="M12 10.5 17 13" />
      <path d="M12 15 9 21" />
      <path d="M12 15 15 21" />
    </IconBase>
  )
);

StretchingIcon.displayName = "StretchingIcon";

export default StretchingIcon;
