import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * StrikethroughIcon ("strikethrough")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const StrikethroughIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 6.5a3.5 3 0 0 1 3.5-2h3a3.5 3 0 0 1 3.3 2.2" />
      <path d="M8 17.5a3.5 3 0 0 0 4 2h1a3.5 3 0 0 0 3.8-2.2" />
      <line x1="4" y1="12" x2="20" y2="12" />
    </IconBase>
  )
);

StrikethroughIcon.displayName = "StrikethroughIcon";

export default StrikethroughIcon;
