import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SubmarineIcon ("submarine")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SubmarineIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 14a9 4.5 0 0 1 18 0 9 4.5 0 0 1-18 0Z" />
      <line x1="12" y1="9.5" x2="12" y2="6" />
      <circle cx="12" cy="5" r="1" />
      <circle cx="9" cy="14" r="1" fill="currentColor" stroke="none" />
      <circle cx="12" cy="14" r="1" fill="currentColor" stroke="none" />
      <circle cx="15" cy="14" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

SubmarineIcon.displayName = "SubmarineIcon";

export default SubmarineIcon;
