import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SunriseIcon ("sunrise")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SunriseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 18h18" />
      <path d="M6 18a6 6 0 0 1 12 0" />
      <polyline points="9.5 7 12 4 14.5 7" />
    </IconBase>
  )
);

SunriseIcon.displayName = "SunriseIcon";

export default SunriseIcon;
