import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SwatchIcon ("swatch")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SwatchIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3.5" y="3.5" width="4.5" height="17" rx="1.5" />
      <rect x="10" y="3.5" width="4.5" height="17" rx="1.5" />
      <rect x="16.5" y="3.5" width="4.5" height="17" rx="1.5" />
    </IconBase>
  )
);

SwatchIcon.displayName = "SwatchIcon";

export default SwatchIcon;
