import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SyncIcon ("sync")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SyncIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 12a8 8 0 0 1 14.5-4.6" />
      <polyline points="18.5 3 18.5 7.5 14 7.5" />
      <path d="M20 12a8 8 0 0 1-14.5 4.6" />
      <polyline points="5.5 21 5.5 16.5 10 16.5" />
    </IconBase>
  )
);

SyncIcon.displayName = "SyncIcon";

export default SyncIcon;
