import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * SyringeIcon ("syringe")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const SyringeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="20" y1="4" x2="16.5" y2="7.5" />
      <path d="M18 6 15 9l-8.5 8.5L4 19l1.5-2.5L14 8Z" />
      <line x1="11.5" y1="6.5" x2="14" y2="9" />
      <line x1="9" y1="9" x2="11.5" y2="11.5" />
      <line x1="4" y1="19" x2="6.5" y2="16.5" />
    </IconBase>
  )
);

SyringeIcon.displayName = "SyringeIcon";

export default SyringeIcon;
