import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TabletIcon ("tablet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TabletIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="5" y="2.5" width="14" height="19" rx="2" />
      <line x1="10.5" y1="19" x2="13.5" y2="19" />
    </IconBase>
  )
);

TabletIcon.displayName = "TabletIcon";

export default TabletIcon;
