import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TagIcon ("tag")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TagIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M11.5 3.5H4.5a1 1 0 0 0-1 1v7l9.6 9.6a1 1 0 0 0 1.4 0l6.6-6.6a1 1 0 0 0 0-1.4Z" />
      <circle cx="8" cy="8" r="1.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

TagIcon.displayName = "TagIcon";

export default TagIcon;
