import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TaxiIcon ("taxi")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TaxiIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 16.5v-3.8L6 8h12l2 4.7v3.8" />
      <line x1="4" y1="16.5" x2="20" y2="16.5" />
      <rect x="10" y="5" width="4" height="2.2" rx="0.5" />
      <circle cx="7.5" cy="16.5" r="1.7" />
      <circle cx="16.5" cy="16.5" r="1.7" />
    </IconBase>
  )
);

TaxiIcon.displayName = "TaxiIcon";

export default TaxiIcon;
