import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TelescopeIcon ("telescope")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TelescopeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="20.5" x2="8" y2="14" />
      <path d="M3 12.5 17 6l1.5 3-14 6.5Z" />
      <line x1="17.5" y1="4" x2="20.5" y2="9.5" />
      <line x1="10" y1="9" x2="12" y2="13" />
    </IconBase>
  )
);

TelescopeIcon.displayName = "TelescopeIcon";

export default TelescopeIcon;
