import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TerminalIcon ("terminal")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TerminalIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="4" width="19" height="16" rx="2" />
      <polyline points="6.5 9 10.5 12 6.5 15" />
      <line x1="12.5" y1="15" x2="17.5" y2="15" />
    </IconBase>
  )
);

TerminalIcon.displayName = "TerminalIcon";

export default TerminalIcon;
