import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ThumbsDownIcon ("thumbs-down")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ThumbsDownIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M17 3v10.5" />
      <path d="M17 13.5 13 20.5a1.8 1.8 0 0 1-3.2-1.6l1.5-4.4H5a2 2 0 0 1-2-2.4l1.5-7A2 2 0 0 1 6.5 3H17Z" />
    </IconBase>
  )
);

ThumbsDownIcon.displayName = "ThumbsDownIcon";

export default ThumbsDownIcon;
