import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ThumbsUpIcon ("thumbs-up")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ThumbsUpIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 21V10.5" />
      <path d="M7 10.5 11 3.5a1.8 1.8 0 0 1 3.2 1.6L12.7 9.5H19a2 2 0 0 1 2 2.4l-1.5 7A2 2 0 0 1 17.5 21H10a3 3 0 0 1-3-3Z" />
    </IconBase>
  )
);

ThumbsUpIcon.displayName = "ThumbsUpIcon";

export default ThumbsUpIcon;
