import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ToggleLeftIcon ("toggle-left")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ToggleLeftIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="7" width="19" height="10" rx="5" />
      <circle cx="8" cy="12" r="3.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

ToggleLeftIcon.displayName = "ToggleLeftIcon";

export default ToggleLeftIcon;
