import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ToggleRightIcon ("toggle-right")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ToggleRightIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="7" width="19" height="10" rx="5" />
      <circle cx="16" cy="12" r="3.2" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

ToggleRightIcon.displayName = "ToggleRightIcon";

export default ToggleRightIcon;
