import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ToolboxIcon ("toolbox")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ToolboxIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="9" width="19" height="10" rx="1.5" />
      <path d="M8 9V6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v3" />
      <line x1="2.5" y1="13.5" x2="21.5" y2="13.5" />
      <line x1="10.5" y1="13.5" x2="10.5" y2="15.5" />
      <line x1="13.5" y1="13.5" x2="13.5" y2="15.5" />
    </IconBase>
  )
);

ToolboxIcon.displayName = "ToolboxIcon";

export default ToolboxIcon;
