import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ToothIcon ("tooth")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ToothIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 4c-3 0-5.5 1.7-5.5 5 0 2 .5 3 1 5.5.4 2 .5 4.5 2 4.5s1.5-3 2.5-3 1 3 2.5 3 1.6-2.5 2-4.5c.5-2.5 1-3.5 1-5.5 0-3.3-2.5-5-5.5-5Z" />
    </IconBase>
  )
);

ToothIcon.displayName = "ToothIcon";

export default ToothIcon;
