import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TornadoIcon ("tornado")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TornadoIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <line x1="4" y1="4" x2="20" y2="4" />
      <line x1="6" y1="8.5" x2="18" y2="8.5" />
      <line x1="8" y1="13" x2="16" y2="13" />
      <line x1="10" y1="17.5" x2="14" y2="17.5" />
      <line x1="11" y1="21" x2="13" y2="21" />
    </IconBase>
  )
);

TornadoIcon.displayName = "TornadoIcon";

export default TornadoIcon;
