import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TractorIcon ("tractor")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TractorIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="7" cy="18" r="3" />
      <circle cx="18" cy="18" r="2.3" />
      <path d="M4 18V9h6l4 4h3a2 2 0 0 1 2 2v3" />
      <line x1="10" y1="9" x2="10" y2="5" />
      <line x1="10" y1="5" x2="7" y2="5" />
    </IconBase>
  )
);

TractorIcon.displayName = "TractorIcon";

export default TractorIcon;
