import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TrainIcon ("train")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TrainIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="6" y="3.5" width="12" height="13" rx="3" />
      <line x1="6" y1="10.5" x2="18" y2="10.5" />
      <circle cx="9.5" cy="13.5" r="1" fill="currentColor" stroke="none" />
      <circle cx="14.5" cy="13.5" r="1" fill="currentColor" stroke="none" />
      <path d="M8 16.5 5.5 20.5" />
      <path d="M16 16.5 18.5 20.5" />
    </IconBase>
  )
);

TrainIcon.displayName = "TrainIcon";

export default TrainIcon;
