import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TrapezoidIcon ("trapezoid")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TrapezoidIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 4h10l4 16H3Z" />
    </IconBase>
  )
);

TrapezoidIcon.displayName = "TrapezoidIcon";

export default TrapezoidIcon;
