import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TreeIcon ("tree")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TreeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3 6 12h3l-4 6h4v4h6v-4h4l-4-6h3Z" />
    </IconBase>
  )
);

TreeIcon.displayName = "TreeIcon";

export default TreeIcon;
