import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TrophyIcon ("trophy")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TrophyIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3.5h10v5a5 5 0 0 1-10 0Z" />
      <path d="M7 5H4a3 3 0 0 0 3 6" />
      <path d="M17 5h3a3 3 0 0 1-3 6" />
      <line x1="12" y1="13.5" x2="12" y2="17.5" />
      <line x1="8.5" y1="20.5" x2="15.5" y2="20.5" />
      <path d="M9 20.5c0-2 1-3 3-3s3 1 3 3" />
    </IconBase>
  )
);

TrophyIcon.displayName = "TrophyIcon";

export default TrophyIcon;
