import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TruckIcon ("truck")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TruckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="8.5" width="11" height="8" rx="1" />
      <path d="M13.5 11h4l3 3.2v2.3h-7Z" />
      <circle cx="7" cy="18.3" r="1.7" />
      <circle cx="17" cy="18.3" r="1.7" />
    </IconBase>
  )
);

TruckIcon.displayName = "TruckIcon";

export default TruckIcon;
