import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TurtleIcon ("turtle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TurtleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 9a4 4 0 0 1 8 0c2.5 0 4.5 1.8 4.5 4.5S18.5 18 16 18H8c-2.5 0-4.5-1.8-4.5-4.5S5.5 9 8 9Z" />
      <circle cx="12" cy="12.5" r="2.3" />
      <path d="M4 12 1.5 10.5" />
      <path d="M4 15 1.5 16.5" />
      <path d="M20 12l2.5-1.5" />
      <path d="M20 15l2.5 1.5" />
      <path d="M10.5 18 9.5 21.5" />
      <path d="M13.5 18 14.5 21.5" />
    </IconBase>
  )
);

TurtleIcon.displayName = "TurtleIcon";

export default TurtleIcon;
