import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TvIcon ("tv")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TvIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="5.5" width="19" height="13" rx="2" />
      <line x1="8" y1="21.5" x2="16" y2="21.5" />
      <line x1="9" y1="2.5" x2="6" y2="5.5" />
      <line x1="15" y1="2.5" x2="18" y2="5.5" />
    </IconBase>
  )
);

TvIcon.displayName = "TvIcon";

export default TvIcon;
