import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * TypeIcon ("type")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const TypeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polyline points="4 6.5 4 4.5 20 4.5 20 6.5" />
      <line x1="12" y1="4.5" x2="12" y2="19.5" />
      <line x1="9" y1="19.5" x2="15" y2="19.5" />
    </IconBase>
  )
);

TypeIcon.displayName = "TypeIcon";

export default TypeIcon;
