import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UmbrellaIcon ("umbrella")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UmbrellaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3a9 9 0 0 1 9 9H3a9 9 0 0 1 9-9Z" />
      <line x1="12" y1="12" x2="12" y2="19.5" />
      <path d="M12 19.5a2 2 0 0 0 4 0" />
    </IconBase>
  )
);

UmbrellaIcon.displayName = "UmbrellaIcon";

export default UmbrellaIcon;
