import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UnpinIcon ("unpin")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UnpinIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 2.5a5.5 5.5 0 0 0-5.5 5.5c0 3 2 4.5 3.5 6l2 6 2-6c1.5-1.5 3.5-3 3.5-6A5.5 5.5 0 0 0 12 2.5Z" />
      <line x1="3" y1="3" x2="21" y2="21" />
    </IconBase>
  )
);

UnpinIcon.displayName = "UnpinIcon";

export default UnpinIcon;
