import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UploadCloudIcon ("upload-cloud")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UploadCloudIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6.5 18.5a4.5 4.5 0 0 1-.4-9 6 6 0 0 1 11.6-1.9A4.5 4.5 0 0 1 17 18.5H14" />
      <polyline points="9.5 14 12 11.5 14.5 14" />
      <line x1="12" y1="11.5" x2="12" y2="20" />
    </IconBase>
  )
);

UploadCloudIcon.displayName = "UploadCloudIcon";

export default UploadCloudIcon;
