import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UsbIcon ("usb")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UsbIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="7" cy="17" r="2" />
      <circle cx="17" cy="7" r="2" />
      <circle cx="17" cy="17" r="2" />
      <line x1="7" y1="15" x2="7" y2="7" />
      <line x1="7" y1="7" x2="15" y2="7" />
      <line x1="9" y1="17" x2="15" y2="17" />
      <line x1="7" y1="10" x2="10" y2="10" />
    </IconBase>
  )
);

UsbIcon.displayName = "UsbIcon";

export default UsbIcon;
