import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UsersIcon ("users")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UsersIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="8" r="3.3" />
      <path d="M3.5 20a5.5 5 0 0 1 11 0" />
      <path d="M15.5 6a3.3 3.3 0 0 1 0 6.4" />
      <path d="M16 14a5.5 5 0 0 1 4.5 5.7" />
    </IconBase>
  )
);

UsersIcon.displayName = "UsersIcon";

export default UsersIcon;
