import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UserMinusIcon ("user-minus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UserMinusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="8" r="4" />
      <path d="M2.5 20a6.5 5.5 0 0 1 13 0" />
      <line x1="15" y1="9" x2="21" y2="9" />
    </IconBase>
  )
);

UserMinusIcon.displayName = "UserMinusIcon";

export default UserMinusIcon;
