import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UserCheckIcon ("user-check")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UserCheckIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="8" r="4" />
      <path d="M2.5 20a6.5 5.5 0 0 1 13 0" />
      <polyline points="15.5 10 17.5 12 21 7.5" />
    </IconBase>
  )
);

UserCheckIcon.displayName = "UserCheckIcon";

export default UserCheckIcon;
