import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UserPlusIcon ("user-plus")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UserPlusIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="8" r="4" />
      <path d="M2.5 20a6.5 5.5 0 0 1 13 0" />
      <line x1="18" y1="6" x2="18" y2="12" />
      <line x1="15" y1="9" x2="21" y2="9" />
    </IconBase>
  )
);

UserPlusIcon.displayName = "UserPlusIcon";

export default UserPlusIcon;
