import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UserXIcon ("user-x")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UserXIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="8" r="4" />
      <path d="M2.5 20a6.5 5.5 0 0 1 13 0" />
      <line x1="15.5" y1="6.5" x2="20.5" y2="11.5" />
      <line x1="20.5" y1="6.5" x2="15.5" y2="11.5" />
    </IconBase>
  )
);

UserXIcon.displayName = "UserXIcon";

export default UserXIcon;
