import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * UtensilsIcon ("utensils")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const UtensilsIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 2.5v7a2 2 0 0 0 4 0v-7" />
      <line x1="8" y1="2.5" x2="8" y2="21.5" />
      <path d="M17 2.5c-1.5 0-2.5 2-2.5 5s1 5 2.5 5v9" />
    </IconBase>
  )
);

UtensilsIcon.displayName = "UtensilsIcon";

export default UtensilsIcon;
