import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VaultIcon ("vault")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VaultIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="3" y="3" width="18" height="18" rx="2" />
      <circle cx="12" cy="12" r="5" />
      <circle cx="12" cy="12" r="1.3" fill="currentColor" stroke="none" />
      <line x1="12" y1="7" x2="12" y2="8.5" />
      <circle cx="18" cy="7" r="0.8" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

VaultIcon.displayName = "VaultIcon";

export default VaultIcon;
