import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VideoOffIcon ("video-off")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VideoOffIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M16 10.5 21 7v10l-5-3.5" />
      <rect x="3" y="6" width="13" height="12" rx="2" />
      <line x1="3" y1="3" x2="21" y2="21" />
    </IconBase>
  )
);

VideoOffIcon.displayName = "VideoOffIcon";

export default VideoOffIcon;
