import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VoicemailIcon ("voicemail")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VoicemailIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="6" cy="14" r="4" />
      <circle cx="18" cy="14" r="4" />
      <line x1="6" y1="14" x2="18" y2="14" />
    </IconBase>
  )
);

VoicemailIcon.displayName = "VoicemailIcon";

export default VoicemailIcon;
