import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VolcanoIcon ("volcano")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VolcanoIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 20.5 9 7l3 4 3-4 5 13.5Z" />
      <path d="M9 7c0-2 1-3.5 3-4.5" />
      <circle cx="12.5" cy="2" r="0.8" fill="currentColor" stroke="none" />
      <line x1="8" y1="16" x2="16" y2="16" />
    </IconBase>
  )
);

VolcanoIcon.displayName = "VolcanoIcon";

export default VolcanoIcon;
