import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VolleyballIcon ("volleyball")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VolleyballIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <path d="M12 3a9 6 0 0 1 6 9" />
      <path d="M3 13a9 6 0 0 0 9 6" />
      <path d="M6 5.5a9 7 0 0 0 3 12" />
    </IconBase>
  )
);

VolleyballIcon.displayName = "VolleyballIcon";

export default VolleyballIcon;
