import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * VolumeIcon ("volume")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const VolumeIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 9.5v5h4l5 4v-13l-5 4Z" />
      <path d="M16.5 9a5 5 0 0 1 0 6" />
      <path d="M19 6.5a9 9 0 0 1 0 11" />
    </IconBase>
  )
);

VolumeIcon.displayName = "VolumeIcon";

export default VolumeIcon;
