import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WalletIcon ("wallet")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WalletIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3.5 7.5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v1.5H16a3 3 0 0 0 0 6h2.5V17a2 2 0 0 1-2 2h-11a2 2 0 0 1-2-2Z" />
      <circle cx="16.3" cy="12.3" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

WalletIcon.displayName = "WalletIcon";

export default WalletIcon;
