import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WarehouseIcon ("warehouse")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WarehouseIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 10 12 4l9 6v10.5H3Z" />
      <rect x="9.5" y="14" width="5" height="6.5" />
    </IconBase>
  )
);

WarehouseIcon.displayName = "WarehouseIcon";

export default WarehouseIcon;
