import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WatchIcon ("watch")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WatchIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="6.5" />
      <line x1="12" y1="8.5" x2="12" y2="12" />
      <line x1="12" y1="12" x2="14.5" y2="13.5" />
      <path d="M9 5.5V3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2.5" />
      <path d="M9 18.5V21a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-2.5" />
    </IconBase>
  )
);

WatchIcon.displayName = "WatchIcon";

export default WatchIcon;
