import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WatermelonIcon ("watermelon")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WatermelonIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 12a9 9 0 0 1 18 0Z" />
      <path d="M6 12a6 6 0 0 1 12 0Z" />
      <circle cx="9.5" cy="9.5" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="12" cy="8.5" r="0.6" fill="currentColor" stroke="none" />
      <circle cx="14.5" cy="9.5" r="0.6" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

WatermelonIcon.displayName = "WatermelonIcon";

export default WatermelonIcon;
