import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WaterfallIcon ("waterfall")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WaterfallIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M4 3v6a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V3" />
      <line x1="8" y1="13" x2="8" y2="21" />
      <line x1="12" y1="13" x2="12" y2="21" />
      <line x1="16" y1="13" x2="16" y2="21" />
    </IconBase>
  )
);

WaterfallIcon.displayName = "WaterfallIcon";

export default WaterfallIcon;
