import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WaveIcon ("wave")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WaveIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 8a3.5 3.5 0 0 1 7 0 3.5 3.5 0 0 0 7 0 3.5 3.5 0 0 1 7 0" />
      <path d="M2.5 15a3.5 3.5 0 0 1 7 0 3.5 3.5 0 0 0 7 0 3.5 3.5 0 0 1 7 0" />
    </IconBase>
  )
);

WaveIcon.displayName = "WaveIcon";

export default WaveIcon;
