import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WebcamIcon ("webcam")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WebcamIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="9" r="5.5" />
      <circle cx="12" cy="9" r="2" fill="currentColor" stroke="none" />
      <line x1="8" y1="20.5" x2="16" y2="20.5" />
      <line x1="12" y1="14.5" x2="12" y2="20.5" />
    </IconBase>
  )
);

WebcamIcon.displayName = "WebcamIcon";

export default WebcamIcon;
