import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WebhookIcon ("webhook")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WebhookIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M8 17.5a3.5 3.5 0 1 1-3-5.3L9 6.5" />
      <path d="M15.5 6a3.5 3.5 0 0 1 2 6.5l-5.5 3" />
      <path d="M11 20.5a3.5 3.5 0 0 0 5.5-2.9c0-.7-.2-1.3-.5-1.9L13 10" />
      <circle cx="9" cy="6.5" r="1.3" fill="currentColor" stroke="none" />
      <circle cx="17.5" cy="12.5" r="1.3" fill="currentColor" stroke="none" />
      <circle cx="12" cy="19.5" r="1.3" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

WebhookIcon.displayName = "WebhookIcon";

export default WebhookIcon;
