import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WheatIcon ("wheat")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WheatIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M12 3v18" />
      <path d="M12 5c-1.5 0-3 1-3 2.5S10.5 10 12 10" />
      <path d="M12 5c1.5 0 3 1 3 2.5S13.5 10 12 10" />
      <path d="M12 10c-1.5 0-3 1-3 2.5S10.5 15 12 15" />
      <path d="M12 10c1.5 0 3 1 3 2.5S13.5 15 12 15" />
      <path d="M12 15c-1.5 0-3 1-3 2.5" />
      <path d="M12 15c1.5 0 3 1 3 2.5" />
    </IconBase>
  )
);

WheatIcon.displayName = "WheatIcon";

export default WheatIcon;
