import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WheelchairIcon ("wheelchair")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WheelchairIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="9" cy="17" r="4.5" />
      <circle cx="18" cy="19" r="1.3" fill="currentColor" stroke="none" />
      <path d="M9 5.5h2.5" />
      <path d="M9 5.5v8h6l3 5.5" />
      <line x1="9" y1="9.5" x2="14.5" y2="9.5" />
    </IconBase>
  )
);

WheelchairIcon.displayName = "WheelchairIcon";

export default WheelchairIcon;
