import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WhistleIcon ("whistle")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WhistleIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M3 9.5h9a4.5 4.5 0 1 1 0 9H9.5A6.5 6.5 0 0 1 3 12Z" />
      <circle cx="16.5" cy="14" r="1.3" fill="currentColor" stroke="none" />
      <path d="M3 9.5V7h3v2.5" />
    </IconBase>
  )
);

WhistleIcon.displayName = "WhistleIcon";

export default WhistleIcon;
