import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WhiteboardIcon ("whiteboard")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WhiteboardIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <rect x="2.5" y="3.5" width="19" height="14" rx="1.5" />
      <line x1="9" y1="21" x2="15" y2="21" />
      <line x1="12" y1="17.5" x2="12" y2="21" />
      <line x1="6" y1="9" x2="12" y2="9" />
      <line x1="6" y1="12.5" x2="10" y2="12.5" />
    </IconBase>
  )
);

WhiteboardIcon.displayName = "WhiteboardIcon";

export default WhiteboardIcon;
