import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WifiIcon ("wifi")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WifiIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M2.5 9a15 15 0 0 1 19 0" />
      <path d="M5.7 12.7a10.5 10.5 0 0 1 12.6 0" />
      <path d="M8.8 16.3a6 6 0 0 1 6.4 0" />
      <circle cx="12" cy="19.5" r="1" fill="currentColor" stroke="none" />
    </IconBase>
  )
);

WifiIcon.displayName = "WifiIcon";

export default WifiIcon;
