import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WineGlassIcon ("wine-glass")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WineGlassIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M7 3h10l-1 6a4 4 0 0 1-8 0Z" />
      <line x1="12" y1="13" x2="12" y2="19" />
      <line x1="8" y1="21" x2="16" y2="21" />
    </IconBase>
  )
);

WineGlassIcon.displayName = "WineGlassIcon";

export default WineGlassIcon;
