import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WinkIcon ("wink")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WinkIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="12" r="9" />
      <circle cx="9" cy="10" r="1" fill="currentColor" stroke="none" />
      <line x1="14" y1="10" x2="16" y2="10" />
      <path d="M8 14.5a4.5 4 0 0 0 8 0" />
    </IconBase>
  )
);

WinkIcon.displayName = "WinkIcon";

export default WinkIcon;
