import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * WrenchIcon ("wrench")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const WrenchIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M14.5 3.5a5 5 0 0 0-6.8 6l-6.2 6.2a2 2 0 0 0 2.8 2.8l6.2-6.2a5 5 0 0 0 6-6.8l-3.2 3.2-2.6-.6-.6-2.6Z" />
    </IconBase>
  )
);

WrenchIcon.displayName = "WrenchIcon";

export default WrenchIcon;
