import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * YenSignIcon ("yen-sign")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const YenSignIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <path d="M6 4 12 13 18 4" />
      <line x1="12" y1="13" x2="12" y2="21" />
      <line x1="7.5" y1="15" x2="16.5" y2="15" />
      <line x1="7.5" y1="18" x2="16.5" y2="18" />
    </IconBase>
  )
);

YenSignIcon.displayName = "YenSignIcon";

export default YenSignIcon;
