import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * YogaIcon ("yoga")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const YogaIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="12" cy="4.5" r="1.8" />
      <path d="M12 6.5v6" />
      <path d="M12 8 6 13" />
      <path d="M12 8 18 13" />
      <path d="M12 12.5 8 20" />
      <path d="M12 12.5 16 20" />
    </IconBase>
  )
);

YogaIcon.displayName = "YogaIcon";

export default YogaIcon;
