import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ZapIcon ("zap")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ZapIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <polygon points="13 2 4 14 11 14 10 22 20 9 13 9" />
    </IconBase>
  )
);

ZapIcon.displayName = "ZapIcon";

export default ZapIcon;
