import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ZoomOutIcon ("zoom-out")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ZoomOutIcon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
      <circle cx="10.5" cy="10.5" r="7" />
      <line x1="20" y1="20" x2="15.5" y2="15.5" />
      <line x1="7.5" y1="10.5" x2="13.5" y2="10.5" />
    </IconBase>
  )
);

ZoomOutIcon.displayName = "ZoomOutIcon";

export default ZoomOutIcon;
