import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { optimize } from "svgo";
import { icons } from "./icon-defs.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const svgOutDir = path.join(rootDir, "icons-svg");
const componentOutDir = path.join(rootDir, "src", "icons");

function toPascalCase(kebab) {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function indent(svg, spaces = 4) {
  const pad = " ".repeat(spaces);
  return svg
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}

function buildStandaloneSvg(inner) {
  const raw = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n${indent(
    inner,
    2
  )}\n</svg>\n`;
  const result = optimize(raw, {
    multipass: true,
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            removeViewBox: false,
            removeUselessStrokeAndFill: false,
          },
        },
      },
    ],
  });
  return result.data;
}

function buildComponent(name, pascalName, inner) {
  return `import { forwardRef } from "react";
import { IconBase } from "../IconBase";
import type { IconProps } from "../IconBase";

/**
 * ${pascalName}Icon ("${name}")
 * Auto-generated by scripts/generate.mjs -- edit scripts/icon-defs.mjs instead.
 */
export const ${pascalName}Icon = forwardRef<SVGSVGElement, IconProps>(
  (props, ref) => (
    <IconBase ref={ref} {...props}>
${indent(inner, 6)}
    </IconBase>
  )
);

${pascalName}Icon.displayName = "${pascalName}Icon";

export default ${pascalName}Icon;
`;
}

function main() {
  fs.mkdirSync(svgOutDir, { recursive: true });
  fs.mkdirSync(componentOutDir, { recursive: true });

  for (const dir of [svgOutDir, componentOutDir]) {
    for (const file of fs.readdirSync(dir)) {
      fs.rmSync(path.join(dir, file));
    }
  }

  const seen = new Set();
  const exportLines = [];

  for (const { name, svg } of icons) {
    if (seen.has(name)) {
      throw new Error(`Duplicate icon name in icon-defs.mjs: "${name}"`);
    }
    seen.add(name);

    const pascalName = toPascalCase(name);

    fs.writeFileSync(
      path.join(svgOutDir, `${name}.svg`),
      buildStandaloneSvg(svg)
    );

    fs.writeFileSync(
      path.join(componentOutDir, `${pascalName}.tsx`),
      buildComponent(name, pascalName, svg)
    );

    exportLines.push(
      `export { ${pascalName}Icon } from "./icons/${pascalName}";`
    );
  }

  const indexContent = `// Auto-generated by scripts/generate.mjs -- do not edit by hand.
export type { IconProps } from "./IconBase";

${exportLines.join("\n")}
`;

  fs.writeFileSync(path.join(rootDir, "src", "index.ts"), indexContent);

  console.log(`Generated ${icons.length} icons.`);
}

main();
